### PR TITLE
build/RELEASING.md: fix markdown formatting, no change in content

### PR DESCRIPTION
**Pull request by chalin**
If you view the file diff by ignoring whitespace changes, then you'll see that there are only whitespace changes: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2263/files?diff=split&w=1:

>

### CODE REVIEW

**Comment by reyang** [comment]
@chalin would you help us to understand why would we want this change (e.g. what's the benefit)?

**Comment by chalin** [comment]
Hi @reyang 

> @chalin would you help us to understand why would we want this change (e.g. what's the benefit)?

Because the resulting file is easier to read. In particular, it is clearer, because of the proper indentation, which lines belong to any given step.

For example:

- **Before**
  > image
- **After**
  > image

The file is markdown, so doesn't it make sense to use proper markdown syntax?

I was originally going to modify step 16 (about updating the docs), but then noticed the formatting issues with the file. So I chose to submit the format fix first.

I'm working on OTel website improvements, and I'm documenting the current doc-update process for each language -- e.g., see https://github.com/open-telemetry/opentelemetry.io/issues/472

**Comment by reyang** [comment]
@chalin got it, thanks for the context.

+1 on "The file is markdown, so doesn't it make sense to use proper markdown syntax?" 👍 

I think it'll be better if we use `##` header for each step, so if we need extra steps, we don't have to change the numbers all over the place. Doesn't have to be this PR though.

The inline code snippet also has improper indentation that we should fix, again, doesn't have to be in this PR.

**Review by reyang — APPROVED** [review]

**Comment by cijothomas** [comment]
Thanks @chalin for the contribution!
(this doc is a temporary doc for the maintainers to do the release. Temporary till we find time to automate these steps via GH actions.)

**Pull request merged**
