### PR TITLE
Remove upper constraint for Ms.Extensions. dependencies

### PR DESCRIPTION
**Pull request by cijothomas**
Once we get an ack from .NET runtime team that, Msft.Extensions.* packages will always remain backward compatible, we can remove the upper bound restriction on Msft.Extensions package. As of today, we have <6 allowed, blocking .NET 6 preview users.

~~This also ups the minimum version to be 3.1 (instead of 2.1), as this update will be released along 1.2.0 (Nov 2021), and 2.1* packages are out of support then.~~
The minimum version is kept as 2.1, to support Asp.Net Core 2.1 applications which target the .NET Framework.

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by cijothomas** [comment]
https://github.com/dotnet/runtime/issues/50042#issuecomment-884388378

**Comment by reyang** [comment]
We are still working with .NET runtime team to clarify the support policy - `Microsoft.Extension.Logging` version `2.1.x` might be used in some old version of `ASP.NET` (not `ASP.NET Core`) which is has their own lifecycle.
Either we hold this PR for now until we have good clarification, or we merge it for now and prepare for a potential revert/rollback.

**Comment by cijothomas** [comment]
> some old version of ASP.NET (not ASP.NET Core) which has their own lifecycle.

I think this is Asp.Net Core (on .NET Framework), and not the "pure" Asp.Net. For such projects, the targetframework in the csproj would be net46 or net47 etc, but the nuget packages are M.E.** 2.1.*...

**Comment by cijothomas** [comment]
@shirhatti Please check if this looks good!

**Comment by cijothomas** [comment]
> We are still working with .NET runtime team to clarify the support policy - `Microsoft.Extension.Logging` version `2.1.x` might be used in some old version of `ASP.NET` (not `ASP.NET Core`) which has their own lifecycle.
> Either we hold this PR for now until we have good clarification, or we merge it for now and prepare for a potential revert/rollback.

Updated the changes and description accounting for this scenario. Please re-review.

**Review by shirhatti — APPROVED** [review]
Looks good to me!

**Review by reyang — APPROVED** [review]
LGTM.

**Pull request merged**
