### PR TITLE
Remove spaces

### PR DESCRIPTION
**Pull request by keepgoing147**

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
In think this is a positive change, and should be done solution wide. If we were to set .editorconfig's _trimwhitespace_ to `true`, we could apply it to the whole solution.

**Comment by bruno-garcia** [comment]
Be aware that on `.editorconfig` that setting shouldn't be applied for `.md` files.

**Comment by MikeGoldsmith** [comment]
@keepgoing147 do you want to update the .editorconfig and apply solution wide, or would you like some help to do that?

**Comment by keepgoing147** [comment]
@MikeGoldsmith thanks for the feedback, it's very helpful, I didn't think to solve it in one go at first, thanks for share it!

I've pushed a new commit, if I'm wrong, feel free to directly point out.

**Comment by keepgoing147** [comment]
Thanks for kindly help!

**Pull request merged**
