### PR TITLE
Remove OpenTelemetry.SemanticConventions project

### PR DESCRIPTION
**Pull request by reyang**
Follow up https://github.com/open-telemetry/opentelemetry-dotnet/pull/5531#discussion_r1566422512.
If users find the project useful, might be a good fit for the opentelemetry-dotnet-contrib repo.

### CODE REVIEW

**Review by alanwest — APPROVED** [review]
👍 I suggested we drop this project in the SIG meeting. Almost pushed up my branch and opened this PR... guess you beat me to it 😆

**Review by vishweshbankwar — APPROVED** [review]

**Comment by alanwest** [comment]
I just unlisted the package from NuGet... should stop showing in search results shortly.

**Review by rajkumar-rangaraj — APPROVED** [review]

**Comment by CodeBlanch** [comment]
What is the urgency here? What we talked about on the SIG was we would land #5531 and then do this as a follow-up. Now I have to go sort out conflicts. Are we practicing good professional courtesy? What sort of collaborative environment do we want to foster?

**Comment by reyang** [comment]
> What is the urgency here? What we talked about on the SIG was we would land #5531 and then do this as a follow-up. Now I have to go sort out conflicts. Are we practicing good professional courtesy? What sort of collaborative environment do we want to foster?

Are these questions for me?

**Comment by joegoldman2** [comment]
What are the real motivations behind this change? We use this package in our organization to avoid repeating constants for standard attributes across all of our projects. Admittedly, the package wasn't really maintained until now and many constants were outdated, but it's still a useful package.

**Comment by reyang** [comment]
> What are the real motivations behind this change?

Maintenance - this package should not come from the opentelemetry-dotnet repository, opentelemetry-dotnet is only intended for core components such as the API / SDK / plugins required by the specification / infrastructure components.

If there is high demand, opentelemetry-dotnet-contrib is the right place https://github.com/open-telemetry/opentelemetry-dotnet/pull/5539#issue-2246628295.

**Pull request merged**
