### PR TITLE
OpenTelemetry.Instrumentation.StackExchangeRedis memory leak on _cache

### PR DESCRIPTION
**Pull request by JM89**
Fixes #[1943](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1943).

## Changes

In the Flush method of the Redis instrumentation cache, the profiling session is being drained but the entry of the cache isn't removed from the cache. I am proposing the following change so it does not keep the references.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by eddynaka** [comment]
if you make the cache internal, you could create a test to be sure that when disposing/flushing the cache is empty.

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Review by eddynaka — APPROVED** [review]

**Comment by JM89** [comment]
Thank you very much for the approvals. Is there anything else I can do to get this merged?

**Review by reyang — APPROVED** [review]
LGTM.

**Pull request merged**
