### PR TITLE
chore: bump OT dependency

### LINKED ISSUE #240: Update OpenTracing bridge to target newest OT C# lib
OpenTracing 0.12.1 has been published so the OT bridge needs to be updated as well.

### PR DESCRIPTION
**Pull request by bruno-garcia**
Related to #240 

/cc @austinlparker

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Based on @austinlparker comment in #240 more things needs to happen here. I will change the description of PR saying it's related, not resolves the issue

**Comment by lmolkova** [comment]
something got wrong with this PR: it's merged but not closed

**Comment by bruno-garcia** [comment]
@lmolkova #240 wasn't closed because it requires code changes now too so the version bump was just the first part.

**Comment by lmolkova** [comment]
ok, still you'd probably need to submit another PR for the rest of the changes, right?

**Comment by bruno-garcia** [comment]
yes. I plan do that on the weekend

**Pull request merged**
