### PR TITLE
Remove application insights exporter

### LINKED ISSUE #645: Remove ApplicationInsights exporter from this repo
Following https://github.com/open-telemetry/opentelemetry-specification/pull/277#discussion_r330265935, we need to move vendor specific exporters away from this repo.
Need to make sure the exporter is registered under https://opentelemetry.io/registry/?s=net.

This needs to go somewhere else: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.ApplicationInsights.

The end result would be having only these exporters in the repo:
* Console
* Jaeger
* Noop
* OpenTelemetryProtocol
* Prometheus
* Zipkin

### PR DESCRIPTION
**Pull request by reyang**
Fixes #645.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@reyang I'm OK if you want to go forward with this. However, I know some people were trying it out like @fbeltrao in this article: https://devblogs.microsoft.com/aspnet/observability-asp-net-core-apps/ and sample: https://github.com/Azure-Samples/application-insights-aspnet-sample-opentelemetry Ideally, some alternative needs to be ready for use before removing.

Let me know if you want to go ahead with it

**Comment by reyang** [comment]
Yes we want to move ahead.
Application Insights exporters will be moved to a separate repo and continue from there.

**Comment by bruno-garcia** [comment]
image
👀

**Comment by stebet** [comment]
Where has the AppInsights exporter been moved to?

**Comment by cijothomas** [comment]
> Where has the AppInsights exporter been moved to?

Nowhere public. It'll resurrect in some Azure/Microsoft owned repo, likely https://github.com/Azure/azure-sdk-for-net.
Details will be announced later this year.

**Comment by reyang** [comment]
The work is in progress https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/monitor/OpenTelemetry.Exporter.AzureMonitor.

**Comment by syedhassaanahmed** [comment]
New link for the Application Insights Exporter https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/monitor/Microsoft.OpenTelemetry.Exporter.AzureMonitor

**Comment by stebet** [comment]
> New link for the Application Insights Exporter https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/monitor/Microsoft.OpenTelemetry.Exporter.AzureMonitor

Thank you :)

**Comment by flcdrg** [comment]
Updated link https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter

**Pull request merged**
