### PR TITLE
Rename SqlClientInstrumentationOptions to SqlClientTraceInstrumentationOptions

### PR DESCRIPTION
**Pull request by Kielek**
Fixes #
Design discussion issue #
Propagate changes from #5109

## Changes

Rename `SqlClientInstrumentationOptions` to `SqlClientTraceInstrumentationOptions`.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by vishweshbankwar — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by alanwest — APPROVED** [review]

**Comment by smoms** [comment]
May I understand how come a breking change like this is just increasing a patch number? Does not follow semantic release? tks

**Comment by vishweshbankwar** [comment]
> May I understand how come a breking change like this is just increasing a patch number? Does not follow semantic release? tks

This component is now moved to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main

Please take a look at this note: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/47b667acf8cde47aa73fc6d28b609ebb3aeca8d3/src/OpenTelemetry.Instrumentation.SqlClient/README.md?plain=1#L15-L29

**Comment by smoms** [comment]
@vishweshbankwar thanks. Does it mean that now the package is being moved to stable?

**Comment by cijothomas** [comment]
> @vishweshbankwar thanks. Does it mean that now the package is being moved to stable?

If you are referring to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.SqlClient, then no. It is not moved to stable.

**Pull request merged**
