### PR TITLE
Enabled C#  8

### LINKED ISSUE #525: Migration to C# 8
Can we update `Directory.Build.props` to use C# 8? It has few nice features that can simplify the code

### PR DESCRIPTION
**Pull request by lukasz-pyrzyk**
Fixes #525

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Is there bunch of warnings around nullable? I remember @bruno-garcia said there will be significant work effort to switch to 8.0

**Comment by lukasz-pyrzyk** [comment]
I don't have any warnings about nullable. As far as I know, we need to enable them globally / for project / for scope to get those warnings

**Comment by bruno-garcia** [comment]
Happy we got C# 8 enabled already. Nullables are opt-in per project through: `<Nullable>enable</Nullable>`. I didn't start with nullable ref types since it'll be a considerable amount of work and I don't want to do 1 project and disappear.

@lukasz-pyrzyk if you're are willing to do that, I was planning to do project by project but it's up for grabs. Could go file by file although not my favorite approach, i.e: `#nullable enable`

**Comment by lukasz-pyrzyk** [comment]
Thanks. I think I'm not gonna pick up nullable reference types right now, I don't have enough knowledge about the project and time to do it correctly

**Comment by bruno-garcia** [comment]
The hardest part is when you get to a point where it's not simply adding `?` or some attribute. 
You actually need to change the code by making it non nullable and refactor all usage of that. Or when something is not supposed to be null but doesn't get assigned via ctor (i.e: EntityFramework).

Also it's worth taking a look at those attribute likes `NotNullWhen(..` for cases like `TrySomething` and out parameters.

For reference: #380 
> While doing this I found a bug on GetHashCode in Trace/Status.cs. Since Description can be null, it would throw.

**Comment by bruno-garcia** [comment]
Oh, just read the *I'm not gonna*. Sorry.
Yeah it's in my TODO list for 3 months now :(

**Comment by lukasz-pyrzyk** [comment]
> The hardest part is when you get to a point where it's not simply adding ? or some attribute.
You actually need to change the code by making it non nullable and refactor all usage of that. Or when something is not supposed to be null but doesn't get assigned via ctor (i.e: EntityFramework).

It's true. Doing it `right` is difficult.

> Oh, just read the I'm not gonna. Sorry.
Yeah it's in my TODO list for 3 months now :(

Maybe, someday! 😄

**Pull request merged**
