### PR TITLE
Remove Resource public ctor as Provider expects ResourceBuilder now

### PR DESCRIPTION
**Pull request by cijothomas**
Fixes #.

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by CodeBlanch — APPROVED** [review]
I left the ctor public for two reasons:

1) Spec specifically calls out a create method on Resource that accepts attributes. The ctor satisfied that nicely. Really Resource class is highly compliant with the spec.
2) You can new up a Resource and pass it to the AddResource method on ResourceBuilder. User is free to do this, if they want to:
   ```csharp
   var builder = ResourceBuilder.CreateEmpty()
      .AddService("MyService")
      .AddResource(new Resource(new Dictionary<string, object> { ["Key1"] = "Value1" }))
      .AddResource(new Resource(new Dictionary<string, object> { ["Key2"] = "Value2" }));
   ```

If you still want to make internal though, fine with me.

**Comment by cijothomas** [comment]
> I left the ctor public for two reasons:
> 
> 1. Spec specifically calls out a create method on Resource that accepts attributes. The ctor satisfied that nicely. Really Resource class is highly compliant with the spec.
> 2. You can new up a Resource and pass it to the AddResource method on ResourceBuilder. User is free to do this, if they want to:
>    ```cs
>    var builder = ResourceBuilder.CreateEmpty()
>       .AddService("MyService")
>       .AddResource(new Resource(new Dictionary<string, object> { ["Key1"] = "Value1" }))
>       .AddResource(new Resource(new Dictionary<string, object> { ["Key2"] = "Value2" }));
>    ```
> 
> If you still want to make internal though, fine with me.

Can I also remove builder.AddResource(Resource) as well? That'll ensure there is only way to create Resource - its through ResourceBuilder.

**Comment by CodeBlanch** [comment]
@cijothomas 

> Can I also remove builder.AddResource(Resource) as well? That'll ensure there is only way to create Resource - its through ResourceBuilder.

Check out `ResourceBuilderExtensions.cs`. All the extensions use `AddResource` to add things to the builder. The `Build()` call just loops through the added `Resource`s and calls `Merge` on them. You could make `AddResource` internal (like `AddDetector`), but then extension authors wouldn't be able to extend the API without some kind of reflection. May or may not be an issue?

**Comment by cijothomas** [comment]
> @cijothomas
> 
> > Can I also remove builder.AddResource(Resource) as well? That'll ensure there is only way to create Resource - its through ResourceBuilder.
> 
> Check out `ResourceBuilderExtensions.cs`. All the extensions use `AddResource` to add things to the builder. The `Build()` call just loops through the added `Resource`s and calls `Merge` on them. You could make `AddResource` internal (like `AddDetector`), but then extension authors wouldn't be able to extend the API without some kind of reflection. May or may not be an issue?

The extensibility for Resource would come through ResourceDetectors - we just need to wait for spec to finalize on that. (https://github.com/open-telemetry/oteps/blob/master/text/0111-auto-resource-detection.md)

But, until then, we can still do the below, right?
```
public static ResourceBuilder AddCijoResource(this ResourceBuilder resourceBuilder)
        {
            // var attributes = populate Cijo Resources;
            return ResourceBuilder.AddAttributes(attributes);
        }
```

**Comment by CodeBlanch** [comment]
@cijothomas

> But, until then, we can still do the below, right?

Ya that would work fine, good call.

**Pull request merged**
