### PR TITLE
Add git submodule for opentelemetry-proto

### LINKED ISSUE #652: Better handling of OTLP proto sources
Separating this from the discussion at #19 

Currently, the proto files are copied to the OTLP exporter sources. At this stage I see two possible options:

1. Use a github submodule;
2. Hack the project to use a nuget source package - of course, in the end, this will require the proto repo to be published in a nuget.

### PR DESCRIPTION
**Pull request by pcwiese**
This change replaces the proto files that were previously copied from the
repo with a direct reference using a git submodule.

People with existing repos will need to initialize the git submodule
before the build will succeed.

```
git submodule init
git submodule update
```

If you are cloning a fresh repo, add the --recursive flag to your clone command.

Fixes #652

### CODE REVIEW

**Comment by reyang** [comment]
Instead of having a submodule dependency, I wonder if we could use a package dependency as it makes things a lot simpler.

FYI - this is how the same problem got solved in OpenCensus: https://github.com/census-instrumentation/opencensus-proto/tree/master/gen-python.

**Comment by pcwiese** [comment]
I'm not a huge fan of git submodules either but it does seem to be the way others are doing it (java for e.g.). If we went with a NuGet package, ideally that would actually get published by the proto repo itself and not here.

**Comment by reyang** [comment]
> I'm not a huge fan of git submodules either but it does seem to be the way others are doing it (java for e.g.). If we went with a NuGet package, ideally that would actually get published by the proto repo itself and not here.

Yep, that's what OpenCensus did (and you can see the link in my previous comment).
We probably need to see what's the feedback from the proto folks, and worst case, having a separate repo that generates the nuget package.

**Comment by pcwiese** [comment]
From the looks of things, I don't think they will be checking in or generating any build assets from the proto repo itself. Somebody just recently removed the gen-go directory (presumably an artifact from opencensus). 

https://github.com/open-telemetry/opentelemetry-proto/commit/6f6985e626954b224ca45f14786b7bcd51c11490

So I think we are left with submodules or setting up another repo to build just this NuGet package. Frankly, I think that may be more overhead than dealing with this. Developers would only have to do this occasionally via the 'git submodule update' command...

**Pull request closed without merging**
