### PR TITLE
Remove Env from CI `DOTNET_MULTILEVEL_LOOKUP = 1`

### PR DESCRIPTION
**Pull request by mic-max**
Towards https://github.com/open-telemetry/opentelemetry-dotnet/issues/3014

Remove `DOTNET_MULTILEVEL_LOOKUP = 1`
I believe it was only needed for .NET Core 3.1 and below

### CODE REVIEW

**Comment by vishweshbankwar** [comment]
Also https://github.com/open-telemetry/opentelemetry-dotnet/blob/3f53be6369aacdde4a5d3baa07987dd44aa9709a/.github/workflows/code-coverage.yml#L24

**Comment by mic-max** [comment]
> Also
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/3f53be6369aacdde4a5d3baa07987dd44aa9709a/.github/workflows/code-coverage.yml#L24

Thanks! I guess I can't trust VS search and should double check with GitHub search 😅

**Comment by reyang** [comment]
> Thanks! I guess I can't trust VS search and should double check with GitHub search 😅

Don't trust GitHub search 😺

**Comment by vishweshbankwar** [comment]
> > Thanks! I guess I can't trust VS search and should double check with GitHub search 😅
> 
> Don't trust GitHub search 😺

I use VS Code :)

**Review by vishweshbankwar — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by utpilla — APPROVED** [review]

**Pull request merged**
