### PR TITLE
[HttpClient] Remove `http.host` and add `net.peer.name` & `net.peer.port` to match spec

### PR DESCRIPTION
**Pull request by vishweshbankwar**
Towards #3373 

## Changes

Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-client

e.g. from spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-client-server-example

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by CodeBlanch** [comment]
This LGTM but FYI it will break the `peer.service` resolution stuff which specifically checks for `http.host`: https://github.com/open-telemetry/opentelemetry-dotnet/blob/131b350d95c6688b1364f174270787656cc9c746/src/OpenTelemetry/Internal/PeerServiceResolver.cs#L31

We should update that code as well for this change (can be done as a follow-up).

**Comment by vishweshbankwar** [comment]
> This LGTM but FYI it will break the `peer.service` resolution stuff which specifically checks for `http.host`:
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/131b350d95c6688b1364f174270787656cc9c746/src/OpenTelemetry/Internal/PeerServiceResolver.cs#L31
> 
> We should update that code as well for this change (can be done as a follow-up).

@CodeBlanch - I am not completely familiar with this part. Do you think that will be a breaking change? Given it will change some logic on resolving `peer.service` in stable exporters?

**Comment by CodeBlanch** [comment]
@vishweshbankwar It will be annoying to people using Jaeger. It has a strange quirk in that unless all services report into the same instance, it won't identify/render spans as dependencies without `peer.service`. Beyond that, hard to say. Not sure what all the possible downstream consumers do with it.

**Comment by vishweshbankwar** [comment]
> @vishweshbankwar It will be annoying to people using Jaeger. It has a strange quirk in that unless all services report into the same instance, it won't identify/render spans as dependencies without `peer.service`. Beyond that, hard to say. Not sure what all the possible downstream consumers do with it.

@CodeBlanch - I looked at this bit more. I think we do not need to change `PeerServiceResolver` as it falls back to looking for `net.peer.name` and `net.peer.port` [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/85da882bbd120a2926508d9ce91483710c097cde/src/OpenTelemetry/Internal/PeerServiceResolver.cs#L83). I was thinking that we need to change for this https://github.com/open-telemetry/opentelemetry-dotnet/pull/3858/files but on checking it looks like we set `peer.service` only for [Client and Producer](https://github.com/open-telemetry/opentelemetry-dotnet/blob/85da882bbd120a2926508d9ce91483710c097cde/src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerActivityExtensions.cs#L101)

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
