### PR TITLE
Rename TraceConfig to TracerConfiguration and remove Default

### PR DESCRIPTION
**Pull request by lmolkova**
TraceConfig should be created once per app lifetime. There is no point in `Default` static instance. A parameterless constructor serves the same need.

### CODE REVIEW

**Comment by austinlparker** [comment]
How would this interact with named tracers/tracer provider? Wouldn't it be possible to have multiple trace configs?

**Comment by lmolkova** [comment]
> How would this interact with named tracers/tracer provider? Wouldn't it be possible to have multiple trace configs?

today TraceFactory takes single config and sets on all tracers and has no way to provide different configurations. 

This change does not prevent Factory from exposing API to configure tracers one-by-one with 
 different configurations. This change only eliminates static Default property by requiring everyone to create instance of config (defaullt or custom).

**Comment by austinlparker** [comment]
Ah, ok, I get it now. Thanks for the clarification!

**Comment by lmolkova** [comment]
@SergeyKanzhelev @austinlparker @discostu105  @bruno-garcia please review

**Comment by lmolkova** [comment]
Somehow I still cannot merge. @austinlparker @SergeyKanzhelev could you approve?

**Comment by bruno-garcia** [comment]
@lmolkova It seems I've joined the org but not the dotnet-approvers team.

**Pull request merged**
