### PR TITLE
Adding test.ruleset to test projects

### PR DESCRIPTION
**Pull request by eddynaka**
Refs #156

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
I see this is already in common.test.props:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/5b9b43cad377cd9673978c8faef3b4b6df841670/build/Common.test.props#L14-L16

But it's inconsistent with the prod code. If you adding ruleset in all projects - please remove it from the common props file

**Comment by eddynaka** [comment]
@SergeyKanzhelev , is it better to maintain the way it is or should i remove from test.props?
And looking at the test.props, we may have to adjust some things:
```xml
<PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <IsTestProject>true</IsTestProject>
    <!--CollectCoverage Condition="$(CollectCoverage) == ''">true</CollectCoverage-->
  </PropertyGroup>
```

we have one project that is a test and doesn't end with tests.

**Comment by SergeyKanzhelev** [comment]
@eddynaka test projects are configured thru this file: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/test/Directory.Build.props Basically based on the folder, not the name of the project. But the same idea.

Trying to recall why we set ruleset per project for product projects - perhaps because they were either `loose` or `prod`. Maybe it would be better to move ruleset definitions to the `Common.props` and `Common.test.props`.

**Comment by eddynaka** [comment]
@SergeyKanzhelev , i will push a new change reverting it.

but, i wouldnt add in the common.props the prod.ruleset, because it will probably break many things. What we can do:
1. Add manually in each product
2. when that finishes, remove all and add to common.

What do you think? And, i will change from:
```xml
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <IsTestProject>true</IsTestProject>
    <!--CollectCoverage Condition="$(CollectCoverage) == ''">true</CollectCoverage-->
  </PropertyGroup>
```
to this:
```xml
  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Test'))">
    <IsTestProject>true</IsTestProject>
    <!--CollectCoverage Condition="$(CollectCoverage) == ''">true</CollectCoverage-->
  </PropertyGroup>
```

Or should i rename just the OpenTelemetry.Collector.AspNet.Tests.Win to OpenTelemetry.Collector.AspNet.Win.Tests?

Let me know! :)

**Pull request merged**
