### PR TITLE
Make HttpClientInstrumentation and SqlClientInstrumentation internal

### PR DESCRIPTION
**Pull request by alanwest**
## Changes
@cijothomas Address small thing you suggested recently. Makes HttpClient and SqlClient instrumentation internal since users should only configure instrumentation using the OpenTelemetryBuilder extension method.

### Checklist
- [X] I ran Unit Tests locally.

### CODE REVIEW

**Comment by CodeBlanch** [comment]
I'm not opposed to this, but every similar "instrumentation" class is currently `public` in the solution so we should probably do it across the board? And also move them into `Implementation` folders?

**Comment by cijothomas** [comment]
> I'm not opposed to this, but every similar "instrumentation" class is currently `public` in the solution so we should probably do it across the board? And also move them into `Implementation` folders?

We can mark every instrumentation as internal.
Regd. moving to implementation folder - we have been doing this from beginning, but can we completely get rid of it? We can use public vs internal, to distinguish between classes meant for public use vs internal/implementation use. Why need additional namespace/folder?

**Comment by alanwest** [comment]
Opps. I was mindlessly poking at my phone yesterday, installed the GitHub app, opened this PR, and clicked the giant `Close` button - which at the time I did not interpret as "close this PR"... anywho...

I'll take a pass and make all instrumentation internal since controlling the public api is most important here.

I also have no problem eliminating the implementation folders. I was going to ask what the intention was behind the additional namespaces, but sounds like there really isn't any, so I support getting rid of them too.

**Comment by cijothomas** [comment]
> Opps. I was mindlessly poking at my phone yesterday, installed the GitHub app, opened this PR, and clicked the giant `Close` button - which at the time I did not interpret as "close this PR"... anywho...
> 
> I'll take a pass and make all instrumentation internal since controlling the public api is most important here.
> 
> I also have no problem eliminating the implementation folders. I was going to ask what the intention was behind the additional namespaces, but sounds like there really isn't any, so I support getting rid of them too.

The only reason why I didnt do this major re-arrangement was that, there was always some PRs open and will likely result in conflicts etc. We need to do a major re-arrangement of folder/namespace, including the test namespace as well to be consistently named. I'm happy to wait for 1-2 week until we ship a beta as well for this rearrangements.

**Comment by alanwest** [comment]
> I'm happy to wait for 1-2 week until we ship a beta as well for this rearrangements.

👍 Sounds good.

Note that I did not touch the StackExchangeRedis instrumentation with this PR. It is a public class, however there exists documentation and code samples that use it directly. Should we consider introducing a builder for this instrumentation?

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs#L32

**Pull request merged**
