### PR TITLE
Add Elastic APM Exporter

### PR DESCRIPTION
**Pull request by glucaci**
Add exporter implementation for Elastic APM (see https://www.elastic.co/guide/en/apm/server/current/events-api.html).

* [ ] Naming ? Elastic.Apm or just Elastic ?
* [ ] Core component ? I don't think so, my question is also why `Jaeger` and `Zipkin` are as core components defined? Because any feature or braking change will change the version of the hole library. In my opinion only `InMemory` and `Console` should be part of core.
* [ ] Span vs Transaction in Elastic. Current approach is that ActivityKind.Internal is a Span the rest are Transactions (see https://www.elastic.co/guide/en/apm/get-started/current/apm-data-model.html)
* [ ] Only .netstandard 2.0 is ok ?

TODO:
* [ ] Tests
* [ ] Add more Span and Transaction properties
* [ ] Add more Metadata properties
* [ ] HttpClient authorization
* [ ] `CHANGELOG.md` updated
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by cijothomas** [comment]
Thanks for your contribution! Since this exporter is not part of Otel spec, please submit this to the contrib repo: https://github.com/open-telemetry/opentelemetry-dotnet-contrib

(Jaeger/Zipkin exporters are defined and required by the spec, and hence is maintained in the main repo.)

**Comment by ejsmith** [comment]
@glucaci this is great! I'd love to see this get added to the contrib project to go along with the Elasticsearch client instrumentation I added there. https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient

**Comment by glucaci** [comment]
Thanks, I will move it to contrib repo.

**Comment by glucaci** [comment]
Done! I will close this one now.

**Pull request closed without merging**
