### PR TITLE
Move Reiley Yang 🐇 to Emeritus👋

### PR DESCRIPTION
**Pull request by reyang**
As we're getting closer to the [1.10.0](https://github.com/open-telemetry/opentelemetry-dotnet/milestone/41) release, it is a good time for me to step back 👋 so I can have more energy to help other incubation workstreams and bring OpenTelemetry to the next level. It is great to see how OpenTelemetry .NET has grown to its current state.

image

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]
Thank you for leadership and guidance!

**Review by Kielek — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]
Thank you, Reiley, for shaping this project to greater success.

**Comment by CodeBlanch** [comment]
Thank you @reyang for all the contributions, guidance, and wisdom you brought to the project. OpenTelemetry overall wouldn't be where it is today without your incredible hard work, dedication, and vison!

**Comment by utpilla** [comment]
Thank you Reiley! You played an instrumental role in driving this project to success. Learned a ton from you while working on this repo.

**Pull request merged**
