### PR TITLE
Open Telemetry Console Exporter Json output

### LINKED ISSUE #5036: I would like to configure Open Telemetry Console Exporter to write using Json Format
# Question
I would like to configure Open Telemetry Console Exporter to write using Json Format. Is there a way? 

## Details
App: Dotnet web api 7.0
Packages:
- OpenTelemetry.Exporter.Console  Version 1.6.0
- OpenTelemetry.Extensions.Hosting  Version 1.6.0
- OpenTelemetry.Instrumentation.AspNetCore  Version 1.6.0-beta.2
- OpenTelemetry.Instrumentation.Http Version 1.6.0-beta.2
- OpenTelemetry.Instrumentation.Runtime  Version 1.5.1

### Setup
```c#
// Logging setup
builder.Logging.ClearProviders();
builder.Logging.AddOpenTelemetry(logging =>
{
    logging.IncludeScopes = true;
    var resourceBuilder = ResourceBuilder
       .CreateDefault()
       .AddService(serviceName);

    logging.SetResourceBuilder(resourceBuilder).AddConsoleExporter(config =>
    {

    });
}).AddConsoleFormatter<CustomFormatter, ConsoleFormatterOptions>();

builder.Services.AddOpenTelemetry()
    // Tracing setup
    .WithTracing(b =>
    {
        b.AddSource(serviceName)
            .ConfigureResource(resource => resource
                .AddService(serviceName: serviceName,
                    serviceVersion: serviceVersion))
            .AddAspNetCoreInstrumentation()
            .AddHttpClientInstrumentation()
            .AddConsoleExporter();
    })
    // Metrics setup
    .WithMetrics(builder => builder
        .AddAspNetCoreInstrumentation()
        .AddRuntimeInstrumentation()
        .AddHttpClientInstrumentation()
        .AddConsoleExporter());
```

### Output:
```sh
Activity.TraceId:            4957f2d7c3d7449acbd8a2eee5c7726c
Activity.SpanId:             b507258da46529d6
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: Microsoft.AspNetCore
Activity.DisplayName:        SampleRoute
Activity.Kind:               Server
Activity.StartTime:          2023-11-09T20:44:17.1290533Z
Activity.Duration:           00:00:00.0463293
Activity.Tags:
    net.host.name: localhost
    net.host.port: 7096
    http.method: GET
    http.scheme: https
    http.target: /SampleRoute
    http.url: https://localhost:7096/SampleRoute
    http.flavor: 2.0
    http.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
    http.route: SampleRoute
    http.status_code: 200
Resource associated with Activity:
    service.name: MyService
    service.version: 1.0.0
    service.instance.id: eb0de8e3-42e4-4576-823f-71fff55a4b28
    telemetry.sdk.name: opentelemetry
    telemetry.sdk.language: dotnet
    telemetry.sdk.version: 1.6.0
```

### Desired output:
```json
{
    "Activity": { 
        "TraceId":  "4957f2d7c3d7449acbd8a2eee5c7726c"
        "SpanId":   "b507258da46529d6"
         "...": "..."
}
```

### PR DESCRIPTION
**Pull request by meijeran**
Fixes #5036 
Design discussion issue #

## Changes

Please provide a brief description of the changes here.

This is an attempt to solve #5036, I switched the current output to a json variant.
I am not sure if we want to keep the original output as well and add the json variant as an extra option. According the comments in  #4548  only one output format is highly favored.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by CodeBlanch** [comment]
I definitely think some options/levers are going to be needed.

* The primary use case today for ConsoleExporter is dev/debug/test. The main thing we need for this is readability. I don't think JSON is too bad but some have suggested `YAML` might be better. Or a very simple text format. We could have options to pick one with the most simple/easy to read as the default. We don't have to start with the options or multiple formats those could be added later but I would be interested to see a comparison for the change her vs what we have today.

* The use case users seem to be asking for on the issue is for production output to use with scraping of stdout. This is a very different thing. I think for this we need the JSON to be compact (single-line per entry). Also it should probably use [JSON Protobuf Encoding](https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding) (example: [trace.json](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.3.0/examples/trace.json)). We probably also need to improve the performance to make it production ready but that doesn't need to happen on this PR. Do we even want the ConsoleExporter to be this thing? Or perhaps could we have a StandardOutputExporter in contrib or something which is purpose built for this scenario? We _could_ document ConsoleExporter is only supported for dev/debug/test and link to the other thing for users who want to scrape. Just an idea 🤔

So my question is really which scenario is this for? Does this really fix/resolve the issue?

**Comment by cijothomas** [comment]
ConsoleExporter is explicitly not recommended for production scenarios. There is no spec written for ensuring consistent output. And yes, performance is another concern.

For scraping the stdout, a better option is to use collector, and have it output to stdout.

**Comment by cijothomas** [comment]
Can you share couple of screenshots of the new behavior as well?

**Comment by meijeran** [comment]
So currently it looks like this

image

image

**Comment by reyang** [comment]
Is this JSON format the same as the proto JSON format or a custom one? https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#json-lines-file

**Comment by meijeran** [comment]
It is not the proto json format is it just a serialized Activity

**Comment by cijothomas** [comment]
> I definitely think some options/levers are going to be needed.
> 
> * The primary use case today for ConsoleExporter is dev/debug/test. The main thing we need for this is readability. I don't think JSON is too bad but some have suggested `YAML` might be better. Or a very simple text format. We could have options to pick one with the most simple/easy to read as the default. We don't have to start with the options or multiple formats those could be added later but I would be interested to see a comparison for the change her vs what we have today.
> * The use case users seem to be asking for on the issue is for production output to use with scraping of stdout. This is a very different thing. I think for this we need the JSON to be compact (single-line per entry). Also it should probably use [JSON Protobuf Encoding](https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding) (example: [trace.json](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.3.0/examples/trace.json)). We probably also need to improve the performance to make it production ready but that doesn't need to happen on this PR. Do we even want the ConsoleExporter to be this thing? Or perhaps could we have a StandardOutputExporter in contrib or something which is purpose built for this scenario? We _could_ document ConsoleExporter is only supported for dev/debug/test and link to the other thing for users who want to scrape. Just an idea 🤔
> 
> So my question is really which scenario is this for? Does this really fix/resolve the issue?

@meijeran Could you reply to the above comment? We are trying to see the issues attempted to be resolved with this PR, so as to better review/guide!

**Comment by meijeran** [comment]
@cijothomas Great questions!

The main reason I started this change is because of issue #5036 and some comments from [this discussion](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4548#discussion_r1222170497). There were a few requests to standardize the console output, so this proposal is just an idea to see if we can make that work.

If the goal is to scrape this data, I think having a dedicated exporter in contrib would be the way to go instead of relying on this. But I'm also curious why the other exporter options aren't enough for that.

So, to answer your question, I'm not entirely sure if this fixes the issue completely, but it's something people have been asking for. Would love to hear more thoughts on this!

**Comment by meijeran** [comment]
Is it still worth to continue on this? Happy to help or figuring out to way to make this work

**Comment by reyang** [comment]
> Is it still worth to continue on this? Happy to help or figuring out to way to make this work

I think yes, definitely something we want to improve.

My suggestion: @meijeran would you clarify the goal here? I think it will be either 1) improving the readability of the stdout exporter or 2) supporting OTLP JSON file (including stdout) exporter for better interoperability.

Once the goal is clear, depending on which one you want to tackle, I have different suggestions:
* If the goal is 1) improving the readability of the stdout exporter, I would suggest YAML rather than JSON
* If the goal is 2) supporting OTLP JSON file/stdout exporter, I would suggest doing it in another exporter rather than the OpenTelemetry.Exporter.Console

**Comment by mrmartan** [comment]
Goal 2) for us.

The use case is: we are running apps on k8s. They are logging single line json (the standard dotnet log format/content) to stdout that is being tailed and shipped by promtail/grafana-agent/alloy. We now want to change the format to OTEL compliant logs without changing the sipping mechanism, i.e. keep the k8s stdout approach.

**Comment by tai-yi** [comment]
@meijeran 
Is `Dictionary<string, object>`  better than anonymous class?
It should not work in AOT case.

**Comment by ozkanpakdil** [comment]
Hi @meijeran I was looking for a way to print one line json of debug log and find myself here, looks like they will not merge this, can you publish this as another exporter like meijeran.opentelemetry.exporter.console in nuget,org and I can use it ?

**Pull request closed without merging**
