### PR TITLE
Move Utkarsh to Approver

### PR DESCRIPTION
**Pull request by utpilla**
As I informed the other maintainers and approvers already, I would be spending my time more on helping with another OpenTelemetry SIG. Therefore, I would be stepping down to an Approver for this SIG.

### CODE REVIEW

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]
Many thanks for all your contributions to this repo!

**Review by reyang — APPROVED** [review]

**Review by Kielek — APPROVED** [review]
Utkarsh, thanks for all your contribution!

**Review by vishweshbankwar — APPROVED** [review]
Thank you for all the contributions, Utkarsh!

**Comment by cijothomas** [comment]
A PR from Utkarsh, which improved Metrics perf significantly! Hoping to replicate this in other languages!
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2805#issuecomment-1019034904

**Comment by CodeBlanch** [comment]
Thanks @utpilla good luck on Rust!

**Pull request merged**
