### PR TITLE
Configure GrpcChannel

### PR DESCRIPTION
**Pull request by akruglikov**
Fixes #
Were added the ability to configure GrpcChannel.  

## Changes

Were added the ability to configure GrpcChannel.  

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by akruglikov** [comment]
This is necessary to use GrpcWeb,
and also allows us to set up ssl-certificates between the server and clients.

**Comment by reyang** [comment]
> @vishweshbankwar This is necessary to use GrpcWeb, and also allows us to set up ssl-certificates between the server and clients.

This PR doesn't seem to be heading towards the right direction.

Check the spec here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options and search for OTEL_EXPORTER_OTLP_CERTIFICATE. If there are additional feature request that is not covered by the spec, create a spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/new/choose.

**Review by reyang — CHANGES_REQUESTED** [review]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5555#issuecomment-2067380525

**Comment by reyang** [comment]
Might be related to #4731.

**Comment by akruglikov** [comment]
> > @vishweshbankwar This is necessary to use GrpcWeb, and also allows us to set up ssl-certificates between the server and clients.
> 
> This PR doesn't seem to be heading towards the right direction.
> 
> Check the spec here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options and search for OTEL_EXPORTER_OTLP_CERTIFICATE. If there are additional feature request that is not covered by the spec, create a spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/new/choose.

Maybe. 

But, at the moment I don't see possibility to set certificate for otlp, I can't switch to 'http/json',  can't use other opportunities that are provided by GrpcChannelOptions.

And another approach which implemented here [4731](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4731) also not finished.

**Pull request closed without merging**
