### PR TITLE
Most flexibility provides gRPC connection

### LINKED ISSUE #4813: Grpc exporter doesn't follow dns change.
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.OpenTelemetryProtocol 1.5.1

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

## Symptom

When i changed dns ip, grpc exporter still connected the old ip.

**What is the expected behavior?**

Grpc connect to new ip.

**What is the actual behavior?**

Grpc still connected the old ip long after i change dns.

## Reproduce

``` C#
var builder = WebApplication.CreateBuilder(args);

var meter = new Meter("Test");

var counter = meter.CreateObservableUpDownCounter("test.counter", () =>
{
    Console.WriteLine(DateTimeOffset.Now);

    return DateTimeOffset.Now.ToUnixTimeMilliseconds();
});

builder.Services
    .Configure<MetricReaderOptions>(options => options.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 10000)
    .AddOpenTelemetry()
    .WithMetrics(mpb => mpb.AddMeter(meter.Name)
        .AddOtlpExporter(options => options.Endpoint = new Uri("http://collector.foo.com:4317")));

var app = builder.Build();

app.Run();
```

1. Set collector.foo.com = ip1 in local host file.
2. Open wireshark 1, start capturing TCP packet, set filter `ip.addr == ip1 && tcp.port = 4317`.
3. Open wireshark 2, start capturing TCP packet, set filter `ip.addr == ip2 && tcp.port = 4317`.
4. Run test code.
5. TCP data will appear in wireshark 1.
6. Modify collector.foo.com = ip2 in local host file.
7. TCP data still in wireshark 1 rather than wireshark 2.

## Additional Context

Grpc.Net use `SocketsHttpHandler` in .net6.0 and SocketsHttpHandler.PooledConnectionLifetime is [InfiniteTimeSpan](https://github.com/dotnet/runtime/blob/08b66559ed06d4d97fb09dfa0d20163f0865deef/src/libraries/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L26C1-L26C1).

[GrpcChannel.ForAddress(options.Endpoint)](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L46) have no any options, so `SocketsHttpHandler` will use default settings. If grpc exporter is used every [1 minute](https://github.com/dotnet/runtime/blob/08b66559ed06d4d97fb09dfa0d20163f0865deef/src/libraries/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L27), the http connection will never be disposed and always use the old connection, so there need to use the `GrpcClientFactory` instead.

> Http exporter already uses [HttpClientFactory](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L114).

### PR DESCRIPTION
**Pull request by pengweiqhca**
Fixes #4813

## Changes

Add `OtlpExporterOptions.HttpHandlerFactory` property to get a HttpHandler.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by vishweshbankwar** [comment]
@pengweiqhca Thanks for the PR. We are currently working on releasing 1.6.0. We will review the issue and PR sometime next week. Thanks for your patience.

**Comment by AB027PS** [comment]
This also fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/4771.

**Review by vishweshbankwar — CHANGES_REQUESTED** [review]
@pengweiqhca Could you please provide more detailed steps for repro on this (Please update the issue)? Once we have a repro, we will then explore the possible solution.

**Comment by jviau** [comment]
I'd recommend not exposing HTTP at all in the options, instead allow for a `Grpc.Core.Api.CallInvoker` to be provided. This will work with both `Grpc.Net.Client` as well as `Grpc.Core`. It will give the most flexibility with how a user provides their desired gRPC connection.

**Comment by pengweiqhca** [comment]
@vishweshbankwar I has change the repro.
@jviau This is a good idea, it is possible for log, trace, and metrics to use the same Grpc channel.

**Comment by cvi-mft** [comment]
Why was this closed?

**Comment by alexander-kucherov** [comment]
Why this PR was closed? I also need this changes

**Comment by alexander-kucherov** [comment]
Any news ?

**Comment by CodeBlanch** [comment]
@alexander-kucherov We're currently working to remove the grpc library dependencies from the OtlpExporter. This particular API won't be possible to expose in that design. I think the best thing to do is open an issue with what you want to do, what the current blockers are. We can work to expose something once the new design is ready (which should be soon: https://github.com/open-telemetry/opentelemetry-dotnet/milestone/44).

AFAIK @rajkumar-rangaraj's plan at the moment is _everything_ will use `HttpClient` so it may be possible to do what you need via the existing APIs/extension points once the work is complete?

**Pull request closed without merging**
