### PR TITLE
TraceIdRatioBasedSampler + ActivityTraceId.CreateRandom Tests

### PR DESCRIPTION
**Pull request by CodeBlanch**
One of my coworkers reported to me that the `TraceIdRatioBasedSampler` works fine for him on windows/.net4.8 but not on linux/netcoreapp3.1. Adding a test to see what happens when it runs through the CI matrix.

### CODE REVIEW

**Comment by CodeBlanch** [comment]
Everything seems fine so I asked my coworker to look into it more on his side. @cijothomas You want these tests in the code? Could be useful to keep an eye on ActivityTraceId.CreateRandom behavior changes?

**Comment by cijothomas** [comment]
> Everything seems fine so I asked my coworker to look into it more on his side. @cijothomas You want these tests in the code? Could be useful to keep an eye on ActivityTraceId.CreateRandom behavior changes?

If this ([InlineData(0.5D, 100, 40, 60)]) is running stable, then okay to have it merged.

**Comment by CodeBlanch** [comment]
Ya my only concern in merging it is it could be unstable. The 40, 60 params there give it a bit of wiggle room. The "50%" probability has to be within 40% - 60%. I haven't seen it fail yet, so stability _seems_ to be good 🦺

**Review by cijothomas — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Comment by cijothomas** [comment]
Have this failure just now:


[xUnit.net 00:00:12.15]       Assert.True() Failure
[xUnit.net 00:00:12.15]       Expected: True
[xUnit.net 00:00:12.15]       Actual:   False
[xUnit.net 00:00:12.15]       Stack Trace:
[xUnit.net 00:00:12.16]         test\OpenTelemetry.Tests\Trace\TraceIdRatioBasedSamplerTest.cs(121,0): at OpenTelemetry.Trace.Tests.TraceIdRatioBasedSamplerTest.SampleUsingRandomTraceIds(Double probability, Int32 numberOfSpans, Int32 expectedNumberOfSampledSpansLowerInclusive, Nullable`1 expectedNumberOfSampledSpansUpperInclusive)
  Passed OpenTelemetry.Trace.Tests.ExceptionProcessorTest.ActivityStatusNotSetWhenExceptionProcessorNotEnabled [1 ms]
  Failed OpenTelemetry.Trace.Tests.TraceIdRatioBasedSamplerTest.SampleUsingRandomTraceIds(probability: 0.5, numberOfSpans: 100, expectedNumberOfSampledSpansLowerInclusive: 40, expectedNumberOfSampledSpansUpperInclusive: 60) [17 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at OpenTelemetry.Trace.Tests.TraceIdRatioBasedSamplerTest.SampleUsingRandomTraceIds(Double probability, Int32 numberOfSpans, Int32 expectedNumberOfSampledSpansLowerInclusive, Nullable`1 expectedNumberOfSampledSpansUpperInclusive) in D:\a\opentelemetry-dotnet\opentelemetry-dotnet\test\OpenTelemetry.Tests\Trace\TraceIdRatioBasedSamplerTest.cs:line 121

**Pull request merged**
