### PR TITLE
Make SemanticConventions internal

### PR DESCRIPTION
**Pull request by alanwest**
This PR follows up on the discussion from #892 to make `SemanticConventions` class internal.

### CODE REVIEW

**Comment by eddynaka** [comment]
How are we going to handle instrumentation/exporters that won't be in the main repo?

**Comment by alanwest** [comment]
@eddynaka excellent question. Some of the constants are relatively generic and could be useful to instrumentation authors like `http.url`, though some of the others are technology specific like `db.redis.database_index` and kinda feels funny to expose maybe? 🤷.

That said, if the future is that instrumentation authors will primarily not be taking an OTel dependency and instead using the ActivitySource API then this isn't really a concern.

**Comment by cijothomas** [comment]
@pcwiese Can you share concerns with this, if any. Though I initially said this should be part of Public API, I agree now that this should be not public.

**Comment by cijothomas** [comment]
Merging now to unblock other PRs - We will revisit, if there are outstanding concerns.

**Comment by ejsmith** [comment]
Hmm... that's kind of a bummer. I was using some of those constants. But I guess I can just include the source class in my lib.

**Comment by cijothomas** [comment]
> Hmm... that's kind of a bummer. I was using some of those constants. But I guess I can just include the source class in my lib.

Yes.

**Pull request merged**
