### PR TITLE
Add Vishwesh as an Approver

### PR DESCRIPTION
**Pull request by utpilla**
@vishweshbankwar has been actively contributing to this repo for a few months now and has demonstrated sufficient technical expertise.

Contributions include active reviews, major improvements to instrumentation libraries, expanding test coverage and documentation, and actively responding to the community via issues.

Link to all the PRs submitted by Vishwesh: https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3Avishweshbankwar

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by alanwest — APPROVED** [review]
Woot, welcome, Vishwesh! 🎉

**Review by CodeBlanch — APPROVED** [review]
Congrats @vishweshbankwar!

**Comment by vishweshbankwar** [comment]
Thank you, All!. Looking forward to further collaborate and contribute.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements-2 Proposed by maintainer and approved by all other maintainers. Merging.

@vishweshbankwar Welcome!

**Pull request merged**
