### PR TITLE
Update AddHttpClientInstrumentation for .NET Framework

### PR DESCRIPTION
**Pull request by utpilla**
Currently, `AddHttpClientInstrumentation` extension method for `.NET Framework` uses both `HttpClientInstrumentationOptions` and `HttpWebRequestInstrumentationOptions` as arguments. This causes confusion to a lot of users who want to configure the `HttpWebRequestInstrumentationOptions` but end up configuring `HttpClientInstrumentationOptions` as that's the first argument of the extension method and both the options classes have some common properties with the same types.

If `HttpClient` is used in .NET Framework it uses `HttpWebRequest` so we only need `HttpWebRequestInstrumentationOptions`. There is a possibility of someone using a .NET Core version of `HttpClient` in a .NET Framework application in which case we might need the `HttpClientInstrumentationOptions` but using `HttpClient` in that way is not recommended.

## Changes
- Update `AddHttpClientInstrumentation` extension method for .NET Framework to only use `HttpWebRequestInstrumentationOptions` as an argument

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [x] Changes in public API reviewed

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]
Thanks! This looks good.

**Review by cijothomas — APPROVED** [review]

**Review by alanwest — APPROVED** [review]

**Comment by alanwest** [comment]
I definitely think this improves things for usability in what we think is the most common case. Worst case if it does turn out that supporting configuring options for .NET Framework apps that consume the HttpClient nuget package is needed then maybe it could be a separate extension method.

**Review by CodeBlanch — APPROVED** [review]
LGTM

Might be worth noting in the docs for the instrumentation that `HttpClient` on .NET Framework uses `HttpWebRequest` internally and will fire `HttpWebRequestInstrumentationOptions.Enrich\Filter` callbacks.

**Comment by cijothomas** [comment]
The docs already call out difference between .NET FX and .NET Core cases. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http#filter

**Comment by cijothomas** [comment]
> The docs already call out difference between .NET FX and .NET Core cases. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http#filter

I'll make it more clear that its .NET FX vs .NET Core, and not HttpClient vs HttpWebRequest and mention about the fact that HttpClient internally is HttpWebRequest in .NET Fx.

**Pull request merged**
