### PR TITLE
Remove Moq dependency

### PR DESCRIPTION
**Pull request by ngruson**
Refactor unit tests in order to remove the `Moq` dependency.

## Changes

Mocks of `TextMapPropagator` have been removed.
I've introduced a `CustomTextMapPropagator` to be able to inject arbitrary key value pairs in the context of a unit test.
@vishweshbankwar : can you agree with this approach?

The dependency to the Moq package has been removed from all the test projects.
Mocking is now done using NSubstitute where needed.

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (nullable enabled, static analysis, etc.)
* [X] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by ngruson** [comment]
Another option could be to use `NSubstitute` instead of `Moq` but I saw https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2816 only after I did my changes.

**Comment by ngruson** [comment]
@vishweshbankwar : To remove the dependency to NSubstitute, more work needs to be done.
It probably involves adding implementations of classes that are now mocked.
Do you want me to try that or in a different PR?

**Comment by Yun-Ting** [comment]
FYI - this PR is related to this issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4758#issuecomment-1702531106

**Comment by utpilla** [comment]
> @ngruson We would like to avoid dependency on both NSubstitute and Mock. I'd suggest to tackle this one project at a time. For the current PR, lets scope this to Http one (as you had earlier) and move on to others in separate PRs.

💯

**Pull request closed without merging**
