### PR TITLE
Remove build badge

### PR DESCRIPTION
**Pull request by reyang**
I looked at the current build badge and the GitHub Actions official badge, neither supports per branch build status. Removing it since it is not going to be very useful at this stage.

### CODE REVIEW

**Comment by bruno-garcia** [comment]
I believe you can set the branch, like:

https://github.com/getsentry/sentry-dotnet/workflows/build/badge.svg?branch=main

**Comment by bruno-garcia** [comment]
Would need to choose one of the workflows though. The badge points to a specific workflow file

**Comment by reyang** [comment]
Yes, we have many workflows, one approach is to pick the most famous one (e.g. Linux and Windows, or perhaps Integration Test).

**Review by cijothomas — APPROVED** [review]
We can discuss and find a "critical" workflow and display it.

**Pull request merged**
