### PR TITLE
[sdk] Expose the ctor on Batch<T> which accepts a single item

### PR DESCRIPTION
**Pull request by CodeBlanch**
To help resolve: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1814

## Changes

* Expose the ctor on `Batch<T>` which accepts a single item for the batch.

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [X] Unit tests added/updated
* [X] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by CodeBlanch** [comment]
@reyang is going to explore doing something with attributes to allow users to opt-into having `SimpleExportProcessor` switch into a reentrant/non-blocking mode. Going to keep this in draft to give him time to investigate that and then we can decide which direction to take.

**Comment by reyang** [comment]
I have a different idea how to solve this (and a category of similar problems), check #5643.

**Comment by CodeBlanch** [comment]
Re-opening this PR.

There are some good alternative proposals in #5643 and #5758 however @alanwest and I feel we need to wait for the spec to prescribe what to do before moving forward: https://github.com/open-telemetry/opentelemetry-specification/issues/4231#issuecomment-2417599886.

We have decided to expose this ctor in the meantime to unblock users.

The spec says `SDK MUST allow users to implement and configure custom processors`. What GenevaExporter wants to do (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1814) is make a custom processor which exports a single item and does not block. Having this ctor makes it possible to implement that in a safe and efficient way. The SDK shouldn't block this valid scenario from being supported/successful.

When the spec defines a concurrent simple processor it will be supported. But users should still be able to make custom implementations whatever they may be regardless.

**Review by alanwest — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]
Thanks!

**Pull request merged**
