### PR TITLE
[sdk-logs] Introduce ConfigureOpenTelemetry ILoggingBuilder extension (proposal 1)

### PR DESCRIPTION
**Pull request by CodeBlanch**
Relates to #4433

/cc @noahfalk

## Changes

* Introduce `ILoggingBuilder.ConfigureOpenTelemetry` extension for configuring `LoggerProviderBuilder`
* Introduce `LoggerProviderBuilder.ConfigureLoggerOptions` extension for configuring `OpenTelemetryLoggerOptions`

## Details

Today we configure logging like this:

```csharp
appBuilder.Logging.AddOpenTelemetry(options =>
{
   options.IncludeFormattedMessage = true;
   options.AddConsoleExporter();
});
```

"options" is `OpenTelemetryLoggerOptions` class.

Now the OpenTelemetry Specification has `LoggerProvider` and we have a `LoggerProviderBuilder` API. The SDK `LoggerProvider` is fed into the `ILogger` integration (`OpenTelemetryLoggerProvider`).

There are different ways we could approach this. Today we have extensions for logging that target `OpenTelemetryLoggerOptions`. We will need to target `LoggerProviderBuilder` now. We could forever have two versions of every extension, but that seems lame.

This PR is adding a new extension `ConfigureOpenTelemetry` to try and bridge the two worlds. `AddProcessor` and `SetResourceBuilder` on `OpenTelemetryLoggerOptions` would be obsoleted as would our existing extensions on `OpenTelemetryLoggerOptions`.

### API Usage

All of these styles can be interchanged.

```csharp
// Configure OTel via ILoggingBuilder
appBuilder.Logging
   .AddOpenTelemetry(options => options.IncludeFormattedMessage = true)
   .ConfigureOpenTelemetry(builder => builder.AddConsoleExporter());
```

```csharp
// Configure OTel via OpenTelemetryBuilder
appBuilder.Services
   .AddOpenTelemetry()
   .WithLogging(builder => builder.AddConsoleExporter());

// Configure ILogger options via ILoggingBuilder
appBuilder.Logging
   .AddOpenTelemetry(options => options.IncludeFormattedMessage = true)
```

```csharp
// Configure OTel via OpenTelemetryBuilder
appBuilder.Services
   .AddOpenTelemetry()
   .WithLogging(builder => builder.AddConsoleExporter());

// Configure ILogger options via Options API
appBuilder.Services.Configure<OpenTelemetryLoggerOptions>(options => options.IncludeFormattedMessage = true);
```

```csharp
// Configure OTel via ILoggingBuilder
appBuilder.Logging
   .AddOpenTelemetry()
   .ConfigureOpenTelemetry(builder => builder.AddConsoleExporter());

// Configure ILogger options via Options API
appBuilder.Services.Configure<OpenTelemetryLoggerOptions>(options => options.IncludeFormattedMessage = true);
```

```csharp
// Configure OTel via OpenTelemetryBuilder
appBuilder.Services
   .AddOpenTelemetry()
   .WithLogging(builder => builder
      .ConfigureLoggerOptions(options => options.IncludeFormattedMessage = true)
      .AddConsoleExporter());
```

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated

### CODE REVIEW

**Comment by CodeBlanch** [comment]
Note: I updated this to include `ConfigureLoggerOptions` that bit is also on proposal 2 & 3. I think it is useful enough to be part of all 3.

**Comment by samsp-msft** [comment]
I think the ideal pattern is that you can register the Logging integration with OTel, either via logging which you do today, or via OTEL and adding logging to it, so you can setup all the telemetry in one place/off one OTEL object.

I don't think that using WithMetrics() on its own does much today does it until you add either a Meter name or register a provider such as ASPNetCoreMetrics.

**Comment by noahfalk** [comment]
@samsp-msft - Am I paraphrasing your comment correctly? "WithLogging() should not listen to ILogger by default, it should be opt-in"

> I don't think that using WithMetrics() on its own does much today

That is my understanding as well.

**Comment by noahfalk** [comment]
@CodeBlanch - is this draft going to be closed in favor of https://github.com/open-telemetry/opentelemetry-dotnet/pull/4501, or you are evaluating different options side by side to get feedback?

**Comment by CodeBlanch** [comment]
@noahfalk I ended up opening 4 different ones:

* https://github.com/open-telemetry/opentelemetry-dotnet/pull/4496
* https://github.com/open-telemetry/opentelemetry-dotnet/pull/4501
* https://github.com/open-telemetry/opentelemetry-dotnet/pull/4502
* https://github.com/open-telemetry/opentelemetry-dotnet/pull/4506

Going to leave them open for a bit to gather feedback. We'll probably discuss on the next SIG meeting. Hoping one will emerge as the favorite/least bad choice 🤣

**Comment by noahfalk** [comment]
> Hoping one will emerge as the favorite/least bad choice 🤣

Probably no surprise my vote is for 2. Among the rest 1 would be my next choice, 3 and 4 feel very shady.

**Pull request closed without merging**
