### PR TITLE
[perf] Update Stress Test to avoid false sharing

### PR DESCRIPTION
**Pull request by utpilla**
## Motivation for this PR:
- The current implementation of Stress Test involves each worker thread to update the `long[] statistics` array
- The worker threads operate on different memory location as each of them have a dedicated index that they use to update the `statistics` array
- However, this suffers from [false sharing](https://en.wikipedia.org/wiki/False_sharing). Even though the individual threads never operate on the same memory location, the memory locations they access are close enough to each other to end up in the same cache line

## Changes in the PR:
- Introduce a padded struct `MeasurementData` to record updates from each worker thread
- `MeasurementData` struct has a size of 128 bytes (16 fields * 8 bytes) which ensures that when we create an array of `MeasurementData` the individual items end up on different cache lines (most systems would have a cache line size <= 128 bytes)

## Stress Test Results

**Machine details:**

Windows 11 (10.0.26100.2314) (Hyper-V)
Intel Xeon Platinum 8370C CPU 2.80GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 9.0.100

I ran the stress test for two scenarios to compare the difference.
1. When stress testing an empty no-op function, the throughput improved **1.5 times** (went up from ~4.5 B to ~7 B loops per second)
2. When stress testing counter metrics, the throughput improved **1.45 times** (went up from ~40 M to ~58 M loops per second)

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by Kielek — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]
Thanks!

(OTel Rust's stress tests already used padding to achieve this goal, but still it has lower throughput. More work for OTel Rust folks to improve perf🤣 )

I'll run stress tests and share results for main vs this PR, for any easy ref in future!

**Comment by cijothomas** [comment]
.NET 8, Windows

Main
Logs - 52
Traces - 1.9
Metrics - 35

PR
Logs - 58
Traces - 1.8
Metrics - 38

**Comment by utpilla** [comment]
> .NET 8, Windows
> 
> Main Logs - 52 Traces - 1.9 Metrics - 35
> 
> PR Logs - 58 Traces - 1.8 Metrics - 38

@cijothomas Could you also mention if the numbers posted for Metrics were for the Counter or Histogram test? [By default](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/OpenTelemetry.Tests.Stress.Metrics/Program.cs#L124), the stress test for metrics is run for histogram.

**Comment by cijothomas** [comment]
> > .NET 8, Windows
> > Main Logs - 52 Traces - 1.9 Metrics - 35
> > PR Logs - 58 Traces - 1.8 Metrics - 38
> 
> @cijothomas Could you also mention if the numbers posted for Metrics were for the Counter or Histogram test? [By default](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/OpenTelemetry.Tests.Stress.Metrics/Program.cs#L124), the stress test for metrics is run for histogram.

Histogram. I ran the stress test as default only.

**Pull request merged**
