### PR TITLE
Removing AI reference

### LINKED ISSUE #1155: Clean up Application Insights code
Remove legacy stuff from https://github.com/open-telemetry/opentelemetry-dotnet/search?q=applicationinsights&unscoped_q=applicationinsights.

### PR DESCRIPTION
**Pull request by eddynaka**
Fixes #1155

## Changes

Please provide a brief description of the changes here. Update the
`CHANGELOG.md` for non-trivial changes.

For significant contributions please make sure you have completed the following items:

* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by reyang** [comment]
@eddynaka would you change the PR title (e.g. clean up application insights code) to avoid confusion?

**Comment by alanwest** [comment]
@eddynaka if you hang tight and wait for #1150 to merge, then I think this entire `IsInternalUrl` method goes away. I didn't know if the application insights exporter was already fixed up to suppress instrumentation, so I did not remove this yet.

**Comment by CodeBlanch** [comment]
@alanwest I saw your note but I don't even see an AppInsights Exporter so it seemed safe to merge. Maybe we had one at some point?

**Comment by alanwest** [comment]
@CodeBlanch I think it got moved out of the repo to the contrib repo.

**Comment by reyang** [comment]
We had it at some point and [it was removed by me](#658) in order to speed up the OpenTelemetry .NET progress.
Microsoft will work on it in [another repo](https://github.com/open-telemetry/opentelemetry-dotnet/pull/658#issuecomment-679218738).
In this OpenTelemetry .NET repo, we don't need to worry about breaking external dependencies before GA. And after GA we'll have to keep the semver promise.

**Comment by CodeBlanch** [comment]
> @CodeBlanch I think it got moved out of the repo to the contrib repo.

@alanwest Ya I thought so too but I checked and it's the instrumentation, not the exporter.

**Pull request merged**
