### PR TITLE
Updated microservice example projects to support c# 10 during docker builds

### LINKED ISSUE #2676: Microservice example fails to build
# Bug Report

## Symptom

When trying to run the microservice example, the docker builds fail.

**What is the expected behavior?**

The docker-compose.yml file in the folder will build and start up containers for all four images.

**What is the actual behavWhat did you see instead?ior?**

The zipkin and rabbitmq images were pulled, but builds of webapi and workerservice would fail, stopping the process.

## Reproduce

Starting at the root of the repo, run the following commands:
1. `git checkout master`
2. `cd ./examples/MicroserviceExample/`
3. `docker-compose up --build`

## Additional Context

It looks like this started with #2599, if you pull the commit on #2591 then it works again. #2599 updated some of the dependencies to c# 10, and since the example gets built inside a netcore 3.1 container, there's a compatibility issue. I'll submit a PR to update the microservice example to net 6.0. Given the nature of the two projects, I'm hoping this won't be an issue, the actual target framework doesn't seem the focus of them.

### PR DESCRIPTION
**Pull request by ktmitton**
Updated the target frameworks for the microservice example projects to net6.0 to support the c# 10 requirement during build through the docker pipeline

Fixes #2676.

## Changes

* Changed the target frameworks of MicroServiceExample/WorkerService and MicroServiceExample/WebApi to net6.0
* Updated the associated Dockerfiles to use the net6.0 images

### CODE REVIEW

**Comment by reyang** [comment]
@ktmitton thanks for the contribution, would you clear the CLA?

image

**Comment by ktmitton** [comment]
> @ktmitton thanks for the contribution, would you clear the CLA?
> 
> image

Trying to, but for some reason it's not taking. I'll have to revisit this tomorrow, sorry.

**Comment by ktmitton** [comment]
> @ktmitton thanks for the contribution, would you clear the CLA?
> 
> image

Ok, looks like it's good now. First time I've had to use this, sorry for the inconvenience!

**Review by cijothomas — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Pull request merged**
