### PR TITLE
[Tiny] Fix 'dotnet test OpenTelemetry.sln' out of Windows

### PR DESCRIPTION
**Pull request by pjanotti**
The test requires VS to run but even with mono, it fails at run time since it references types that only exist on Windows .NET Framework.

Using a simple workaround: not including the test runner outside of Windows.

### Checklist
- [X] I ran Unit Tests locally.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
this fix may be a replacement for this code:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/dacae6d50fe56a64eba8585a154a1d80c1ae860d/OpenTelemetry.proj#L5-L9

you can run `dotnet test OpenTelemetry.proj`, but I agree it's counterintuitive

**Comment by SergeyKanzhelev** [comment]
Do you have an idea how to disable compilation of the entire project? @tarekgh can you advice if you saw anything like this? Can we disable compilation of the project on windows by setting some flag on the top?

**Comment by pjanotti** [comment]
Hi :wave: @tarekgh nice to "see you" around here!

@SergeyKanzhelev I tried `dotnet test OpenTelemetry.proj` but it errors with 
```terminal
open-telemetry/opentelemetry-dotnet/OpenTelemetry.proj : error MSB4057: The target "VSTest" does not exist in the project.
```

**Comment by tarekgh** [comment]
@pjanotti I am glad to hear from you. hope everything going well on your side.

@SergeyKanzhelev the way currently done in https://github.com/open-telemetry/opentelemetry-dotnet/blob/dacae6d50fe56a64eba8585a154a1d80c1ae860d/OpenTelemetry.proj#L5-L9 is the right way to include or exclude projects. 
If you want to do something on the csproj itself, it is possible but it is tricky and I wouldn't recommend it. one example is to override the "Build" target for MSBuild. 

```Xml
<Target Name="Build" Condition="'$(OS)' == 'Linux'" />
```
I said tricky too because you to ensure the order of defining this target. 

Now, the question is, should the project be allowed to compile even on none Windows but not run there?

**Comment by pjanotti** [comment]
> should the project be allowed to compile even on none Windows but not run there?

My tendency is to let it build since avoids people accidentally breaking it by working on non-Windows machines. To be fair there is one test that can pass on non-Windows if one has VSTools installed.

**Comment by tarekgh** [comment]
> To be fair there is one test that can pass on non-Windows if one has VSTools installed.

Should this be configured on the test case levels to decide which test should run on which OS? like ConditionalFact/ConditionalTheaory ideas.

**Comment by pjanotti** [comment]
> like ConditionalFact/ConditionalTheaory ideas.

Combined with a conditional to check for VSTools presence it can work, I will give it a spin later.

**Comment by SergeyKanzhelev** [comment]
I remember the issue was that the corresponding product code was missing some targets on Mac to be actually build. So perhaps it needs to be excluded. If it works, let's just merge this PR. Just let me know.

**Comment by pjanotti** [comment]
ok @SergeyKanzhelev let's merge it as it is, there is a bit of work to bring conditional attributes and so on...

**Pull request merged**
