### PR TITLE
[Instrumentation.Http] Change Activity Source Name for HttpWebRequests

### PR DESCRIPTION
**Pull request by Kielek**
Fixes N/A.

## Changes

[Instrumentation.Http] Change Activity Source Name for `HttpWebRequest`s from `OpenTelemetry.HttpWebRequest` to `OpenTelemetry.Instrumentation.Http`.

If we need a different name than for other HttpWebRequests we could use `OpenTelemetry.Instrumentation.HttpWebRequest`

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* ~~[ ] Design discussion issue #~~
* ~~[ ] Changes in public API reviewed~~

### CODE REVIEW

**Comment by utpilla** [comment]
I think we should have the distinction between HttpWebRequest and the newer HttpClient instrumentations. So, we could instead just rename the ActivitySource to `OpenTelemetry.Instrumentation.HttpWebRequest`.

@cijothomas  Thoughts?

**Comment by Kielek** [comment]
@utpilla, @cijothomas, there is a new PR #3515.
I do not have strong opinion which version will be better.
Please keep in mind that this field is serialized as `otel.library.name`, so I would prefer this PR.

Please merge one of them, and close the second one.

**Comment by alanwest** [comment]
> Please keep in mind that this field is serialized as `otel.library.name`, so I would prefer this PR.

Non-OTLP exporters (e.g Zipkin and Jaeger) produce this attribute as a way to map the name and version of an ActivitySource. This used to referred to as the "instrumentation library" name and version. Though there was a somewhat recent change to instead refer to this as "instrumentation scope".

As such, non-OTLP exporters are supposed to also map this to `otel.scope.name` and `otel.scope.version` now. See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/mapping-to-non-otlp.md#instrumentationscope

> I think we should have the distinction between HttpWebRequest and the newer HttpClient instrumentations. So, we could instead just rename the ActivitySource to OpenTelemetry.Instrumentation.HttpWebRequest.

I agree maintaining a distinction is useful. My vote is #3515.

**Comment by Kielek** [comment]
Closing. Changes should be handled in scope of #3515.

**Pull request closed without merging**
