### PR TITLE
Fix IDE0090: 'new' expression can be simplified.

### PR DESCRIPTION
**Pull request by tillig**
Continues work on #3001.

## Changes

Fixes all IDE0090 issues such that obvious object construction uses the `new()` syntax instead of `new T()`. Analyzer rule `csharp_style_implicit_object_creation_when_type_is_apparent` explicitly set to `true:suggestion` which is the default behavior, but calling it out helps indicate to folks that it's also the _desired_ value for the project and it's cool to fix those if you see them.

```c#
// var uses remain the same
var x = new Thing();

// explicit types like in class fields switch to new()
Thing x = new();
```

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
Merging without waiting for more reviews. Safe change. Touches a large number of files, so waiting longer could result in merge conflicts.

**Comment by tillig** [comment]
I made an unfortunate error in the title for the PR (just the title) - this was IDE0063, not IDE0090. IDE0090 is simplifying object initialization and that's still to come.

```c#
/// from this
var x = new Foo();
x.Thing = 2;

/// to this
var x = new Foo
{
  Thing = 2
};
```

Sorry about the mix-up. 😦

**Comment by tillig** [comment]
I fixed the title and initial comment but that won't change the [merge commit message here](https://github.com/open-telemetry/opentelemetry-dotnet/commit/d55de344f19875ee09faddf6e4420f56be7b3958). Someone with owner abilities will have to do something like `git rebase` or `git --amend` to fix it. It's probably not that important in the long run, but... again, sorry.

**Comment by cijothomas** [comment]
> It's probably not that important in the long run

I think we can live with that. Appreciate your thoroughness in every PRs :)

**Pull request merged**
