### PR TITLE
New ApiCompat

### LINKED ISSUE #2081: ApiCompat improvements
Copied from https://github.com/open-telemetry/opentelemetry-dotnet/issues/1711#issuecomment-860815199

.NET Team is moving this tool into a separate package, along with other compact check tools. We'll need to adjust accordingly as it happens. - @utpilla

Only enabled for core packages now, as only core packages have ever released stable package. Need to update this once non-core components also release stable. - @cijothomas

The check is part of a non-mandatory CI now, as the tool itself is new and we don't want to break existing CI if the tool has issues. Once the tool is stable, (expected by .NET 6 release time), we can make this CI check mandatory. @cijothomas

The CI check is failing today. @utpilla has investigated this and opened dotnet/arcade#7511, as this is likely a tooling issue. @utpilla

Need to update the release process, so that every stable release updates the "base or contract" version to check compat against. @cijothomas

### PR DESCRIPTION
**Pull request by mic-max**
Fixes #2081 

## Changes

- Added dotnet package validation following this guide: https://devblogs.microsoft.com/dotnet/package-validation
- Had to increase `LangVersion` from `8.0` to `10.0` due to this error
  - `F:\Git\mic-max\opentelemetry-dotnet\src\OpenTelemetry\obj\Debug\net6.0\OpenTelemetry.ImplicitNamespaceImports.cs(8,1): error CS8400: Feature 'global using directive' is not available in C# 8.0. Please use language version 10.0 or greater. [F:\Git\mic-max\opentelemetry-dotnet\src\OpenTelemetry\OpenTelemetry.csproj]`

`PackageVersion` and `PackageValidationBaselineVersion` need to be decided on.

### CODE REVIEW

**Comment by mic-max** [comment]
Questions:
- Should the work done in https://github.com/open-telemetry/opentelemetry-dotnet/pull/2075 be fully replaced by this one?
- Should all `.publicApi` folders be deleted?
"update the release process, so that every stable release updates the "base or contract" version to check compat against" where is this process?
- Will this workflow https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/workflows/apicompatibility.yml remain and we add a `dotnet pack` command to the end?

**Comment by mic-max** [comment]
I was able to get the compiler to complain to me about both the examples from the article:
- When a function being added with signature `A` existed in net6 and existed with signature `B` in other net versions
- When an existing function is altered to have a different signature than what it had in the `.csproj` specific previous release.
  - I'm guessing `Microsoft.Dotnet.PackageValidation` downloads that versions specification from NuGet to use for this comparison?

Note: These errors occur during the `dotnet pack` command rather than the `dotnet build` command.

**Comment by utpilla** [comment]
> Questions:
> 
> * Should the work done in [Using Microsoft.DotNet.ApiCompat #2075](https://github.com/open-telemetry/opentelemetry-dotnet/pull/2075) be fully replaced by this one?

We would want to replace ApiCompat checks with PackageValidation eventually. PackageValidation will be release with .NET 6 so we will have to wait until it's stable.

> * Should all `.publicApi` folders be deleted?

Refer to @cijothomas 's comment here: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2075#issuecomment-858760280

>   "update the release process, so that every stable release updates the "base or contract" version to check compat against" where is this process?

This is done when calling the [powershell script](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d355697038ca2093a1dc52822c98578840ad2d69/build/Common.prod.props#L23) to install the base contract assemblies. After every stable release, `OTelPreviousStableVer` in Common.props should be updated.

> * Will this workflow https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/workflows/apicompatibility.yml remain and we add a `dotnet pack` command to the end?

You can create a new workflow until the time we get rid of ApiCompat. This workflow calls the powershell script to install the base contract assemblies.

**Comment by utpilla** [comment]
> Note: These errors occur during the `dotnet pack` command rather than the `dotnet build` command.

This is expected. ApiCompat checks compatibility for assemblies so it only needs to build. PackageValidation checks compatibility for `.nupkg` files so it needs to pack.

**Comment by mic-max** [comment]
Build from the work done in this PR https://github.com/dotnet/aspnetcore/pull/35846 👍

**Pull request closed without merging**
