### PR TITLE
Added unit tests for SuppressInstrumentationScope

### PR DESCRIPTION
**Pull request by utpilla**
## Changes
- Added unit tests for SuppressInstrumentationScope

### CODE REVIEW

**Review by reyang — APPROVED** [review]
LGTM.

**Comment by utpilla** [comment]
Closing and reopening the PR to trigger Build tests.

**Comment by ThomsonTan** [comment]
> Closing and reopening the PR to trigger Build tests.

Curious about the reopening. Are some some tests not run? If so, an [empty commit](https://coderwall.com/p/vkdekq/git-commit-allow-empty) could be pushed to trigger re-run CI.

**Comment by utpilla** [comment]
> > Closing and reopening the PR to trigger Build tests.
> 
> Curious about the reopening. Are some some tests not run? If so, an [empty commit](https://coderwall.com/p/vkdekq/git-commit-allow-empty) could be pushed to trigger re-run CI.

Thanks @ThomsonTan ! Yeah tests were not being run, I'll follow the empty commit approach from now on.

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
