### PR TITLE
Introduce DistributedContextBuilder

### LINKED ISSUE #374: DistributedContext - values of "bigger scope" must be inherited
If i defined a larger scope with the value "appVersion=1.0" and later smaller scope with the property "flightID=Foo" I want both properties to be propagated downstream. Without manually merging these two collections

It is expected to inherit scopes. But there should be a mechanism to

- wipe it and start fresh (typical for situation you enter some "hostile" code that will call into external services)
- remove/overwrite certain keys

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #374

This change mainly to address the scenarios listed in #374 and add more flexibility for creating distributed contexts. Here are some notes regarding the change:
-	DistributedContext can be created only through the builder.
-	No real change in the DistributedContext semantic behavior. It stays read-only immutable object.
-	The builder has a constructor to allow inheriting the current context entries. The builder can start from a clean list too.
-	Builder can allow adding (which technically adding or updating) entries. Also, it supports removing entries. 
-	The builder has static factory methods for creating a context object for simple scenarios that don’t require adding/removing entries.
-	Builder is optimized to reduce allocations, so when calling Build() it will use the underlying buffer to create the context without allocating and copying the list. That means after Build() call, the builder will reset to empty list again. I believe this will serve the perf for the main scenario.

### CODE REVIEW

**Comment by tarekgh** [comment]
Thanks @MikeGoldsmith for the review and info.

**Comment by tarekgh** [comment]
@SergeyKanzhelev let me know if you are fine with the change and we can merge this one.

**Comment by tarekgh** [comment]
@SergeyKanzhelev please have a look.

**Comment by SergeyKanzhelev** [comment]
@tarekgh can you please merge to master?

**Comment by tarekgh** [comment]
@SergeyKanzhelev done merging to master.

**Pull request merged**
