### PR TITLE
[sdk-logs] Add Transform API on batch

### PR DESCRIPTION
**Pull request by CodeBlanch**
## Changes

* Added `Transform` API on `Batch<T>` which can be used to modify and/or filter
  records contained in a batch

## Details

Ran into an issue with a customer doing this (more or less):

```csharp
        private ExportResult Export(in Batch<LogRecord> batch)
        {
            LogRecord[] storage = ArrayPool<LogRecord>.Shared.Rent((int)batch.Count);

            try
            {
                int storageCount = 0;
                int redactedFieldCount = 0;

                foreach (var logRecord in batch) // Drains the batch
                {
                    redactedFieldCount += ExecuteRedactionEngine(logRecord);
                    storage[storageCount++] = logRecord;
                }

                if (redactedFieldCount > 0)
                {
                    LogRedactedFieldSummary(redactedFieldCount);
                }          

                // Call inner exporter to actually perform the export
                return innerExporter.Export(
                    new Batch<LogRecord>(storage, storageCount)); // Create a new batch
            }
            finally
            {
                ArrayPool<LogRecord>.Shared.Return(storage);
            }
        }
```

`ExecuteRedactionEngine` is a bunch of logic for inspecting the log record and removing sensitive information. Customer specifically does this over the batch at the time of export to not block the application when it is creating the telemetry.

The issue here is while processing `foreach (var logRecord in batch)` the completed `LogRecord`s may be returned to the pool (if they were rented from it). 

What this PR is proposing to solve this is add a new API on `Batch<T>` which can be used to do this processing safely by mutating an instance of `Batch<T>`:

```csharp
    private ExportResult Export(in Batch<LogRecord> batch)
    {
        var transformationState = new TransformationState
        {
             RedactionEngine = this.RedactionEngine,
        };

        batch.Transform(OnTransformLogRecord, ref this.RedactionEngine);

        if (transformationState.RedactedFieldCount > 0)
        {
            LogRedactedFieldSummary(transformationState.RedactedFieldCount);
        }   

        return innerExporter.Export(in batch);
    }

    private static bool OnTransformLogRecord(LogRecord logRecord, ref TransformationState state)
    {
        state.RedactedFieldCount += state.RedactionEngine.ExecuteRedactionEngine(logRecord);
        return true;
    }

    private struct TransformationState
    {
        public RedactionEngine RedactionEngine;
        public int RedactedFieldCount;
    }
```

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [X] Unit tests added/updated
* [X] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by CodeBlanch** [comment]
@reyang I made some changes to the design after our initial offline discussion. Please take a look when you have a moment and let me know how you feel about it now.

* Renamed from `WithProcessor` -> `Transform`

* Switched the design from executing the transformation as items were read to doing all the work upfront. I liked the previous design better but my concern was it could lead to a case where the batch returns a count which differs from the number of items which would actually be read out (in the case of filtering). Probably wouldn't be an issue for most exporters, but it _could_ be an issue for something so I went with a safe-by-default design.

* In order to do the work upfront I utilized the `ArrayPool` to store the transformed/filtered batch. The rented array has to be returned when the batch processing is done. We could have relied on users calling `Dispose` to do that, but I felt most users would miss that. In order to make it easy & safe I switched the design from returning a new batch to mutating the existing batch. This way users performing transformation/filtering don't need to worry about disposing anything, the batch processor which created it initially will handle that.

**Comment by Kielek** [comment]
@CodeBlanch, the feature looks good, but after short verification with https://github.com/open-telemetry/opentelemetry-specification/tree/v1.35.0 there is no such transformer. I think that it should be defined on the specification level, then we could implement it. For now, it can be hidden by the unstable features.

**Comment by pellared** [comment]
> FYI as you working on similar API for the Go SDK.

This looks like volitation of the SDK specification which does not handle filtering.
CC @open-telemetry/technical-committee

**Comment by CodeBlanch** [comment]
@pellared I hear you, but I don't think it is that cut and dry. This issue is caused by implementation details in .NET. Do other languages have a batch implementation based on a circular buffer backed by records from a pool? 😄 I looked at Java a bit. It seems the batch there is a simple ArrayList or Collection. If users want to massage that batch and then delegate the processing work to some other exporter they may filter, transform, or augment the items, no? This will not work as expected in .NET due to the implementation. The spec doesn't really say much at all about what shape the batch should have. Do we need it to be more opinionated? IMO the situation is we made some perf optimizations which lead to surprising behavior in code which would work with other SDKs. This API is to give users a way to do it safely. IMO it is well within our purview to do that as it is to specialize our implementation(s) in the first place.

PS: Just to be clear this isn't a hypothetical exercise. There are users doing this today and they are currently experiencing data loss 😢

**Comment by pellared** [comment]
Go batching log processor has also a circular buffer. I will do my best to take a look later and compare the implementations. If you want you can look as well: https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/log/batch.go

**Comment by pellared** [comment]
> This API is to give users a way to do it safely. IMO it is well within our purview to do that as it is to specialize our implementation(s) in the first place.

May there other ways on how to do it?

The biggest concern is that you are not only adding "transform" capabilities but also "filtering" which is not covered by the specification. Why wouldn't you like to filter the records before they reach the batching processor?

I assume that adding a "transform" (without filtering capabilities) to the batching exporter will be totally acceptable given the implementation specifics (as you are using a pool).

**Pull request closed without merging**
