### PR TITLE
Add a simple Mermaid diagram for the metrics tutorial

### PR DESCRIPTION
**Pull request by reyang**
Related to #2952.

I wish to see if folks like the idea of having such diagram(s) in the docs.

### CODE REVIEW

**Review by utpilla — APPROVED** [review]

**Comment by utpilla** [comment]
Looks great!!

**Review by cijothomas — APPROVED** [review]
good addition.

I need to learn how to draw this myself.

**Comment by mic-max** [comment]
> good addition.
> 
> I need to learn how to draw this myself.
@reyang Did you use a website or tool to make this? If so could you share it 😃

**Comment by reyang** [comment]
The Mermaid official site has plenty of resources, including a [live editor](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNqVUstOAzEM_JUop0Vtf6DiArQrcUAg9YZWQm5ida1N4hInraD039lHu6ACB3yKxzMT2_JBG7ao59o4EFkQbCL4Kqg2bkHwKbJBEY7q-mM2U4tsmqF4E8iDG9CSpP6JPuM6wgD33hd-h6HUxY5iyq1szezUYyg5GixdlrqgkFQij5zTAzlHgoaDlas_tas6J8v78A_ljsmqBcmWBYvexvYJhc2Jffw-RbeCsffJKsWWp9YIzR07jmNB9uSL8bfJawbTFL_5dcsb_WZd20LveB9KxDTCBsIS0q_6fs1fDfUDkLzsydkRjDlcaM-hp9pj9EC2PYHepdKpRo-VnrdPC7GpdBWOLS9vLSRcWkoc9TzFjFMNOfHqLZhzPnBOVzSAx0_O1cHt).

I also use the VSCode extension "Markdown Preview Mermaid Support", which supports side-by-side preview.

**Pull request merged**
