### PR TITLE
Remove net452 from console exporter project

### PR DESCRIPTION
**Pull request by cijothomas**
Part of https://github.com/open-telemetry/opentelemetry-dotnet/issues/2138
1st of potentially 10s of PRs...
Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [x] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by cijothomas** [comment]
@open-telemetry/dotnet-approvers Want to check thoughts from all on this.
What this means is, when we release the next minor version (1.2.0) in Nov 2021, we'll be cutting support for some frameworks. This might be considered a breaking-change, and warrant a major version bump. 

However, I think we can (and we should) do minor version bump only, considering NET452 support is dropped by DS (which we have hard dependency on), and Net452 will be EOL within 4-5 months of our planned 1.2 release (https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/)

Please share your thoughts.

**Review by CodeBlanch — APPROVED** [review]
Approach LGTM @cijothomas

**Review by bruno-garcia — APPROVED** [review]
> However, I think we can (and we should) do minor version bump only, considering NET452 support is dropped by DS (which we have hard dependency on), and Net452 will be EOL within 4-5 months of our planned 1.2 release

Makes sense to me! 4.6.1 is a very reasonable goal

**Review by reyang — APPROVED** [review]

**Comment by cijothomas** [comment]
@pjanotti To see if any objections from auto-instrumentation side.

**Comment by cijothomas** [comment]
Merging to unblock progress. As we need to do this for a bunch of projects, and then bring the change to metrics branch, before metrics branch can update to newest DS version. If there are concerns/questions, please comment in the issue #2138

**Pull request merged**
