### PR TITLE
Add test validating expected status for AspNetCore instrumentation

### PR DESCRIPTION
**Pull request by alanwest**
Putting this PR out to pose a question related to the recent spec changes to `Status` and the subsequent refactoring.

It appears that on a successful request (i.e., status code in range [100, 399]), `Status` == `Status.Unset`. https://github.com/open-telemetry/opentelemetry-dotnet/blob/378ba54b77690f670c1ab526281d0349e1001348/src/OpenTelemetry.Api/Trace/SpanHelper.cs#L30-L40

As a result, `status.IsOk` == `false`.

Is this the behavior we want? If so, this test documents this behavior. If not, then we should fix the 🐛.

### CODE REVIEW

**Comment by eddynaka** [comment]
Based on the spec, only the customer would set Ok (at least in my understanding). With that in mind, I didn't change the `IsOk` logic. Not sure what is the best answer for this

**Comment by CodeBlanch** [comment]
How I read the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-status), this behavior seems correct to me.

>Generally, Instrumentation Libraries SHOULD NOT set the status code to Ok, unless explicitly configured to do so. Instrumention libraries SHOULD leave the status code as Unset unless there is an error, as described above.

Maybe we should remove IsOk? Could be misleading given the behavior. Or change it to IsOkOrUnset, assuming people will use it as some kind of !Error check?

**Comment by alanwest** [comment]
> Based on the spec, only the customer would set Ok

Make sense.

> `Status.IsOk` is just a helper we added, not from the spec, right?

Yes, just a helper.

> Maybe we should remove IsOk?

I'd support this. Seems a little confusing to have this helper since it will almost always be false for spans generated by instrumentation libraries, and setting the status on such spans is not necessarily straight forward.

The reason this came up for me is that the New Relic exporter currently checks `IsOk` to set an error state on a span that causes it to be show up red in the UI. So, I need to fix this to rely on something besides status.

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
Removing IsOk helper and/or replacing it with IsOkOrUnset can be separate PR.

**Review by reyang — APPROVED** [review]

**Pull request merged**
