### PR TITLE
Avoid the "Win" trick

### PR DESCRIPTION
**Pull request by reyang**
## Changes

Moving forward it will be rare to have Windows-only components, and currently the only Windows specific component is ASP.NET instrumentation.
I made the change to exclude ASP.NET on Linux so we avoid having to introduce the "Win" trick.

### CODE REVIEW

**Comment by cijothomas** [comment]
@reyang @eddynaka I merged other PR which caused a conflict here. May be eddy can help as this is about the .sln file.

**Comment by eddynaka** [comment]
> @reyang @eddynaka I merged other PR which caused a conflict here. May be eddy can help as this is about the .sln file.

@cijothomas , i opened this PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/863 to solve the issue.

**Comment by cijothomas** [comment]
Still has conflicts!?

**Comment by eddynaka** [comment]
> Still has conflicts!?

That's strange. The branch that I created from his branch didn't have any issue after I resolved the merge problems. Reiley probably have to do it.

**Pull request merged**
