### PR TITLE
add honeycomb exporter

### PR DESCRIPTION
**Pull request by lizthegrey**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
hm... I wonder how GitHub allowed to merge this PR with the current branch enforcements... @lizthegrey, curious, did you use some admin powers?

**Comment by lizthegrey** [comment]
Not on purpose. it said "at least one approving OWNER, and tests pass" so good to merge.

Github unfortunately doesn't allow me to distinguish when I'm using special powers vs not and it would be really nice to need to sudo (maybe I should have my admin privs on not-my-primary-account)...

**Comment by MikeGoldsmith** [comment]
We're used to only seeing dotnet maintainers merge things, ie @SergeyKanzhelev or @austinlparker.

**Comment by lizthegrey** [comment]
Ah, yeah, sorry, it was a doc change only, so it seemed like the expedient thing to do but I can avoid doing so :)

**Comment by MikeGoldsmith** [comment]
No complaint, I would have merged quickly too. Just point out what we're used to seeing 👍

**Pull request merged**
