### PR TITLE
Improving code coverage

### PR DESCRIPTION
**Pull request by eddynaka**
Fixes #.

## Changes
- Removing unused methods/constructors
- Adding more tests

For significant contributions please make sure you have completed the following items:

* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by alanwest** [comment]
@eddynaka Looks like some nice improvements to test coverage. I'm generally interested in the approach you're taking to identify things to improve?

**Comment by eddynaka** [comment]
> @eddynaka Looks like some nice improvements to test coverage. I'm generally interested in the approach you're taking to identify things to improve?

Hi @alanwest , i'm using two approaches: vs2019 style and codecov report. From codecov report (https://codecov.io/gh/open-telemetry/opentelemetry-dotnet/tree/feature%2Fimproving-codecoverage/src), we can see which files have the lowest coverage. With that in mind, i started to do that.

**Comment by eddynaka** [comment]
One thing that i still couldn't figure out is how to test EventSource. Injecting all the cases are hard, but at least we had to check the event and writeevent values.

**Comment by alanwest** [comment]
> Hi @alanwest , i'm using two approaches: vs2019 style and codecov report. From codecov report (https://codecov.io/gh/open-telemetry/opentelemetry-dotnet/tree/feature%2Fimproving-codecoverage/src), we can see which files have the lowest coverage. With that in mind, i started to do that.

Cool, thanks for the tip! I'd clicked around codecov a bit, and was just curious about your workflow.

**Comment by eddynaka** [comment]
@alanwest, do u know how to test the event sources somehow?

**Comment by alanwest** [comment]
> @alanwest, do u know how to test the event sources somehow?

@eddynaka Sorry for delay, just seeing this...

Just to be sure, is it the SqlEventSourceTests tests you're looking at? I haven't spent a lot of time looking at this test suite, but I welcome the opportunity at familiarizing myself more! Can you point me to a specific test you'd like to improve?

**Pull request merged**
