### PR TITLE
[AOT] Remove shim for UnconditionalSuppressMessageAttribute and use ifdefs

### PR DESCRIPTION
**Pull request by Yun-Ting**
Fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/4689

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by utpilla — APPROVED** [review]

**Comment by eerhardt** [comment]
I don't see the `UnconditionalSuppressMessageAttribute.cs` file actually being removed. Is there a different PR that deletes the file?

**Comment by reyang** [comment]
> I don't see the `UnconditionalSuppressMessageAttribute.cs` file actually being removed. Is there a different PR that deletes the file?

I guess step by step / in several PRs.

**Comment by eerhardt** [comment]
Then I would re-open https://github.com/open-telemetry/opentelemetry-dotnet/issues/4689 because it isn't fixed until the file is removed.

**Comment by reyang** [comment]
> Then I would re-open #4689 because it isn't fixed until the file is removed.

+1

**Comment by Yun-Ting** [comment]
Sorry for confusion: 
This PR removed the file: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4701

**Pull request merged**
