### PR TITLE
Keys with digits are still accepted

### PR DESCRIPTION
**Pull request by vuqtran88**
According to W3C specs, keys with digits are still accepted. W3C specs state the followings:
"Note: Identifiers MUST begin with a lowercase letter or a digit, and can only contain lowercase letters (a-z), digits (0-9), underscores (_), dashes (-), asterisks (*), and forward slashes (/)."

### CODE REVIEW

**Comment by vuqtran88** [comment]
I surely can

**Comment by MikeGoldsmith** [comment]
@vuqtran88 Let us know if you'd like some help with this, or if you're not going to get to work on it soon. We'd like to get this merged.

**Comment by vuqtran88** [comment]
@MikeGoldsmith 
Sorry, I have been busy with some other tasks. I will get back into this sometimes today.

**Comment by vuqtran88** [comment]
@MikeGoldsmith thanks for approving, does not look like I am authorized to merge this approved PR. Will you merge it ?

**Comment by vuqtran88** [comment]
@lmolkova tests are added, can you lift off the change request ?

**Comment by lmolkova** [comment]
@vuqtran88 sure thing. Thanks for the PR!

**Pull request merged**
