### PR TITLE
Add reference to Instrument on IMetric

### PR DESCRIPTION
**Pull request by alanwest**
We need a handle to the instrument that generates a metric so that we can include description, unit, and meter name/version upon export.

@victlu @cijothomas

### CODE REVIEW

**Review by victlu — DISMISSED** [review]
I don't think this is is correct.

Logically, Instrument is not 1:1 with metric (aka an Aggregator). It is possible for multiple instruments to contribute values to one metric. (Although, recent view spec has limited View configuration to matching only 1 instrument.)

The proposed View API will allow user to configure description. So, if anything, we need metrics to have it's own copy of description, rather than refer to the instrument.

My suggestion would be to expand IMetric to include Description (and maybe Unit) field. And pass in description (from the source Instrument or future View configuration) when we create the MetricAggregator in the AggregatorStore::MapToMetrics().

**Comment by victlu** [comment]
> My suggestion would be to expand IMetric to include Description (and maybe Unit) field. And pass in description (from the source Instrument or future View configuration) when we create the MetricAggregator in the AggregatorStore::MapToMetrics().

Given we also need to populate InstrumentLibrary info for OTLP protocol, then, we will need a reference to the Meter.

**Comment by cijothomas** [comment]
> The proposed View API will allow user to configure description. So, if anything, we need metrics to have it's own copy of description, rather than refer to the instrument.
> 
> My suggestion would be to expand IMetric to include Description (and maybe Unit) field. And pass in description (from the source Instrument or future View configuration) when we create the MetricAggregator in the AggregatorStore::MapToMetrics().

+1

**Review by cijothomas — APPROVED** [review]
LGTM.
If you can modify the Console Exporter to print the meter name,version, unit, description, that'll be a good validation!

**Comment by alanwest** [comment]
> If you can modify the Console Exporter to print the meter name,version, unit, description, that'll be a good validation!

Yep, adding that back right now... will be just a moment

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
