### PR TITLE
refactor!: collector to adapter

### LINKED ISSUE #335: Confusion around collector name
[Collector](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#collector) according to spec is something that forwards telemetry in OTel format over OTLP to intermediate components/backends.

We have API `AddCollector` on `TracerBuilder` which is something that generates spans (e.g. HTTP in or out ). Spec suggests calling them 'adapters' but does not insist on it.

For the sake of common terminology, I propose to rename `AddCollector` to `AddAdapter` and use 'collector'  only in the sense spec uses it (service/daemon/agent)

### PR DESCRIPTION
**Pull request by longility**
Renamed files, directories, solution and project dependencies, namespaces, variables, and docs.

BREAKING CHANGE

closes #335

### CODE REVIEW

**Comment by longility** [comment]
I signed it

**Comment by longility** [comment]
Refactor was pretty straightforward. The only one I questioned that I didn't change is this:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/d48e702286458c14746df430490421c514474544/src/OpenTelemetry.Exporter.LightStep/LightStepTraceExporterOptions.cs#L22

`public Uri Satellite { get; set; } = new Uri("https://collector.lightstep.com:443/api/v2/reports");` in LightStepTraceExporterOptions.csproj

**Comment by longility** [comment]
I signed it

**Comment by longility** [comment]
I put in a support tick as I signed the CLA and tried to trigger through comment, but it is still asking for CLA.

Also, I broke out focused refactoring efforts through commits to give an idea how I approached the refactoring and the related changes.

**Comment by longility** [comment]
I signed it

**Comment by cijothomas** [comment]
@MikeGoldsmith / @SergeyKanzhelev - Please review/merge. Now is a great time as no pending PRs about collectors!

**Comment by longility** [comment]
For transparency, the force push update was a `git pull --rebase` on `master` of opentelemetry-dotnet as there were merge conflicts identified here. When I ran that command locally, it was able to auto-merge.

**Pull request merged**
