### PR TITLE
Set PrometheusExporterMiddleware as public.

### LINKED ISSUE #2776: Prometheus support for middleware injection
Using the Prometheus exporter results in an endpoint which can't be protected by any authentication.

Use case:
We're using the Prometheus exporter to provide metrics for the Prometheus service. Unfortunately the endpoint is reachable for everyone because it does not support a build-in authentication (which I'm totaly fine with).

To protect the endpoint, e.g. with a simple basic authentication, it should be possible to inject a custom middleware.
There are three possible options.

**Option 1**
Provide option to use `PrometheusExporterMiddleware` directly.
```csharp
app.Map("/metrics", metricsApp =>
{
    metricsApp.UseMiddleware<BasicAuthMiddleware>("Contoso Corporation");
    metricsApp.UseOpenTelemetryPrometheusMiddleware();
});
```` 

**Option 2**
Provide injection point:
```csharp
 public static IApplicationBuilder UseOpenTelemetryPrometheusScrapingEndpoint(this IApplicationBuilder app, MeterProvider meterProvider = null, Action<IApplicationBuilder> injectionPoint = null)
{
    var options = app.ApplicationServices.GetOptions<PrometheusExporterOptions>();

    string path = options.ScrapeEndpointPath ?? PrometheusExporterOptions.DefaultScrapeEndpointPath;
    if (!path.StartsWith("/"))
    {
        path = $"/{path}";
    }

    return app.Map(
        new PathString(path),
        builder => {
    injectionPoint ?.Invoke(builder); // <-- inject custom middleware here
    builder.UseMiddleware<PrometheusExporterMiddleware>(meterProvider ?? app.ApplicationServices.GetRequiredService<MeterProvider>()); 
    });
}
```

**Option 3**
Provide build-in (Basic) authentication support, so we don't need to inject a custom middleware.

I'm totaly fine with any option and would provide a PR.

### PR DESCRIPTION
**Pull request by tillig**
Fixes #2776.

## Changes

Updated `PrometheusExporterMiddleware` to be public rather than internal.

## Notes

While [the current `UseOpenTelemetryPrometheusScrapingEndpoint`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/778052f67f58b945be7c046bb57a8f3dc3be57c1/src/OpenTelemetry.Exporter.Prometheus/PrometheusExporterApplicationBuilderExtensions.cs#L43) allows configuration of the Prometheus middleware based on options, it doesn't allow for more flexible options or more tailored handling of the Prometheus endpoint.

My specific use case is that I need to do `app.MapWhen` and include not only _path_ but also _port_.  I can't use the standalone listener on that port because I have _other_ management things like health checks also exposed on that port; but I can't put the `/metrics` endpoint right on the main API listener port, either.

Other options I considered before going with making `PrometheusExporterMiddleware` public:

- **Add port to `PrometheusExporterOptions`**: This seemed like it'd be confusing given there were already `HttpListenerPrefixes` in there. 
- **Create another `UseOpenTelemetryPrometheusScrapingEndpoint` overload that takes a predicate**: Something where you can pass the `Func<HttpContext, bool>` that you pass to `app.MapWhen`. However, that would end up bypassing the `PrometheusExporterOptions` entirely because the predicate would control the whole mapping. It'd be up to the consumer to resolve the options and build the predicate. This didn't seem intuitive.

In the end it seemed like the one thing that would solve all the problems for advanced users while still maintaining the nice, easy `UseOpenTelemetryPrometheusScrapingEndpoint` mechanism was to make `PrometheusExporterMiddleware` public. Advanced users will know that they'll need to manage the `UseMiddleware<T>` and parameter setup; folks looking for the one-liner will still have that ability.

Since the middleware got switched to public I also moved it into the main folder of the OpenTelemetry.Exporter.Prometheus project since it appeared everything in the "Implementation" folder was internal.

### CODE REVIEW

**Comment by tillig** [comment]
Realized after the API compat build ran that I'd forgotten to update the `PrometheusExporterMiddleware` namespace (public items appear to be directly in `OpenTelemetry.Exporter`) and I'd also forgotten to include the constructor in the public API list. Fixed. I think the build should pass now.

There was an earlier failure on SQL Server timing out; I'm not sure what to do about that since I didn't actually change anything around SQL Server.

**Comment by reyang** [comment]
This change will expose the traits that PrometheusExporter is built on top of (e.g. asp.net core, middleware).

The challenge seems to be similar to #2882.

I think we need to make a design decision - do we want PrometheusExporter to hide all the implementation traits or not? If we do need "a special PrometheusExporter that is ASP.NET Core friendly", do we want it to be the same exporter or a separate one? (e.g. what if there is another user saying "I want an OWIN or WCF friendly PrometheusExporter")

**Comment by tillig** [comment]
My goal is to allow the ability to have tighter control over where/how the exporter is attached to my app pipeline. I'm falling into a gray area that isn't covered - it can't be on the same _port_ as the rest of the services, but it also can't be _a standalone listener_, and those are the only options available at the moment.

If you really wanted to hide it, you'd probably have to make some breaking API changes. For example, the `PrometheusExporterOptions` has `HttpListenerPrefixes` and `ScrapeEndpointPath`. You'd need to either add something confusing like `ScrapeEndpointPort` to that (which overlaps in a weird and unintuitive way with `HttpListenerPrefixes`); or you'd need to split the options into two different things - `PrometheusExporterListenerOptions` for the standalone listener and `PrometheusExporterPipelineOptions` (or something like that) for the pipeline-based listener (middleware).

Technically the actual Prometheus format response is generated by the still-internal `CollectionManager`, so if you wanted to add an OWIN or some other exporter, that part is still hidden.

Making the middleware itself public seemed to be a reasonable middle ground where it wouldn't introduce breaking changes, wouldn't add confusing/conflicting options, and would still allow folks like me to have that advanced ability to put the middleware in place in the pipeline with all the configuration we need.

I mean, I'm totally open to other solutions. This just seemed to allow the most flexibility for consumers in the easiest, most non-breaking way possible.

In the meantime, I'm having to do stuff like this to make it work:

```c#
var configuredPath = app.ApplicationServices
  .GetService<IOptions<PrometheusExporterOptions>>()
  ?.Value
  ?.ScrapeEndpointPath;
var path = new PathString(configuredPath ?? "/metrics");

bool Predicate(HttpContext c)
{
  var success =
    (port == null || c.Connection.LocalPort == port) &&
    (!path.HasValue ||
      (c.Request.Path.StartsWithSegments(path, out var remaining) &&
    string.IsNullOrEmpty(remaining)));
  return success;
}

var middlewareType =
  typeof(PrometheusExporterOptions)
    .Assembly.GetType("OpenTelemetry.Exporter.Prometheus.PrometheusExporterMiddleware");
if (middlewareType == null)
{
  throw new InvalidOperationException("Unable to locate the Prometheus exporter middleware type.");
}

return app.MapWhen(
  Predicate,
  b => b.UseMiddleware(middlewareType, app.ApplicationServices.GetRequiredService<MeterProvider>()));
```

That's because

- `PrometheusExporterMiddleware` is internal (gotta use reflection)
- `PrometheusExporterOptions.DefaultScrapeEndpointPath` is internal (gotta hardcode the `/metrics` default)
- There's no way to currently specify a port or `MapWhen`.

**Comment by reyang** [comment]
> If you really wanted to hide it, you'd probably have to make some breaking API changes.

Exactly! The PrometheusExporter is not yet Stable, and [the spec is still Experimental](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/prometheus.md) so we should be able to take breaking changes.

> I mean, I'm totally open to other solutions. This just seemed to allow the most flexibility for consumers in the easiest, most non-breaking way possible.

Given that there were many "HTTP servers" and the space is still evolving, I don't think we will end up with "one fit for all" solution. I would suggest having a neutral PrometheusExporter which is agnostic to the underlying implementation, then having dedicated components (whether as a separate package, or some DI plugins) for concrete hosting (e.g. OWIN, ASP.NET Core).

**Comment by tillig** [comment]
Oh, I see what you're saying - have, like, `OpenTelemetry.Exporter.Prometheus.AspNetCore` with the middleware and the ASP.NET Core listener, plus something similar for ASP.NET, and maybe something for WCF if folks want it.

Of course, if that was added, I'd probably ask for the ability to expose the base exporter common bits so I could write my own exporter extension if needed. Like, right now the middleware "hides" the call to the `CollectionManager` to get the response; that would be part of the public API so I could do that from my own middleware/plugin implementation.

I'd be totally OK with that if that's how the project wants to go.

**Comment by reyang** [comment]
> Oh, I see what you're saying - have, like, `OpenTelemetry.Exporter.Prometheus.AspNetCore` with the middleware and the ASP.NET Core listener, plus something similar for ASP.NET, and maybe something for WCF if folks want it.
> 
> Of course, if that was added, I'd probably ask for the ability to expose the base exporter common bits so I could write my own exporter extension if needed. Like, right now the middleware "hides" the call to the `CollectionManager` to get the response; that would be part of the public API so I could do that from my own middleware/plugin implementation.
> 
> I'd be totally OK with that if that's how the project wants to go.

Exactly! And in the `OpenTelemetry.Exporter.Prometheus.AspNetCore` we can keep adding specific things that are highly related to ASP.NET Core, and yet other folks who use the PrometheusExporter without ASP.NET Core don't have to worry about the extra dependencies (and if they want to have OWIN/WCF specific things, the ASP.NET Core users won't be affected).

**Comment by tillig** [comment]
Cool. I guess, let me know if that's something to proceed with and/or if you'd like a PR for that instead of this.

**Comment by tillig** [comment]
BTW, if you do want help there... I'm a MacOS + VS Code guy, so it'd be good to know if we could add the `.vscode` folder with build/test tasks to make that work better. I could do that, too.

**Comment by reyang** [comment]
> Cool. I guess, let me know if that's something to proceed with and/or if you'd like a PR for that instead of this.

I had similar discussion with @CodeBlanch before, want to see if he has some ideas.

**Comment by reyang** [comment]
> BTW, if you do want help there... I'm a MacOS + VS Code guy, so it'd be good to know if we could add the .vscode folder with build/test tasks to make that work better. I could do that, too.

I do see some other OpenTelemetry projects having `.vscode` folder, for example https://github.com/open-telemetry/opentelemetry-specification/tree/main/.vscode.

I guess it's a choice of the maintainers if they would like to see this project associated with any IDEs or editors. I personally would slightly prefer the project to be neutral (IIRC I was questioning if we need the `*.sln` file at all or not when I joined this project 😆).

**Comment by tillig** [comment]
> I guess it's a choice of the maintainers if they would like to see this project associated with any IDEs or editors.

[The CONTRIBUTING doc currently specifically lists "supported IDEs"](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#linux-or-macos) so having the `.vscode` folder doesn't seem entirely out of the question, but I'm open to whatever. I can always put a local one in if I gotta, it's just a pain after `git clean -dfx` to have to put it all back.

**Comment by reyang** [comment]
> [The CONTRIBUTING doc currently specifically lists "supported IDEs"](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#linux-or-macos) so having the .vscode folder doesn't seem entirely out of the question, but I'm open to whatever. I can always put a local one in if I gotta, it's just a pain after git clean -dfx to have to put it all back.

I'm convinced! 👍😄

**Comment by tillig** [comment]
@reyang Should I abandon this PR in favor of the separate `OpenTelemetry.Exporter.Prometheus.AspNetCore` project idea or is there more discussion to be had? I apologize in advance for being somewhat slow on the uptake, I'm just not clear if I missed the direction here.

**Comment by reyang** [comment]
> @reyang Should I abandon this PR in favor of the separate `OpenTelemetry.Exporter.Prometheus.AspNetCore` project idea or is there more discussion to be had? I apologize in advance for being somewhat slow on the uptake, I'm just not clear if I missed the direction here.

I would suggest that we give 2-3 days for @CodeBlanch to advise here. He has the best knowledge about the PrometheusExporter Middleware. Also adding @alanwest and @cijothomas in case they have a strong preference.

**Comment by cijothomas** [comment]
> > @reyang Should I abandon this PR in favor of the separate `OpenTelemetry.Exporter.Prometheus.AspNetCore` project idea or is there more discussion to be had? I apologize in advance for being somewhat slow on the uptake, I'm just not clear if I missed the direction here.
> 
> I would suggest that we give 2-3 days for @CodeBlanch to advise here. He has the best knowledge about the PrometheusExporter Middleware. Also adding @alanwest and @cijothomas in case they have a strong preference.

We briefly mentioned in last SIG meeting. PrometheusExporter is a bit lower in priority compared to overall Metrics SDK/OTLP Exporter, as we'll likely release Prometheus Stable *after* the stable SDK (spec is also moving in such direction that Prometheus would follow after overall SDK spec..).

In short - need some more time to get to prometheus and iron out its limitations/issues, hopefully @CodeBlanch can help once get some free cycles to chime in here.

**Comment by CodeBlanch** [comment]
@tillig Sorry for the delay in looking at this! I totally get the ask. But I _think_ you can make this work today as-is (with `internal PrometheusExporterMiddleware`). Here are the steps I would take to do it. Please let me know if you tried this and ran into blockers.

Let's say I want to run my main API with HTTPS on port 5000 at the root (`/`) and I want to expose metrics with HTTP on port 5002 at `/admin/metrics` (which I only allow internal traffic to using some appliance).

1. Configure ASP.NET Core URLs. Different ways to do this, one way is environment variable:
   `ASPNETCORE_URLS: https://localhost:5000;http://localhost:5002`

2. Register & configure `PrometheusExporter`:
   ```csharp
      builder.Services.AddOpenTelemetryMetrics(options => options.AddPrometheusExporter());
      builder.Services.Configure<PrometheusExporterOptions>(o => o.ScrapeEndpointPath = "/admin/metrics");
   ```

3. Branch the pipeline:
   ```csharp
      app.MapWhen(
          context => context.Connection.LocalPort == 5002,
          builder => builder.UseOpenTelemetryPrometheusScrapingEndpoint());
   ```

**Comment by tillig** [comment]
@CodeBlanch So, let's say I _already have_ some things that I integrate with that look like this:

```c#
app.UseHealthCheck(5001, "/healthz");
app.UseReadinessCheck(5001, "/readiness");
```

Those effectively boil down to things that do

```c#
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001 && ctx.Request.Path == "/healthz",
  b => b.UseMiddleware<HealthCheckMiddleware>());
```

like that. I'm trying to integrate this in there, too, so what I need to be able to do (to make sure people don't hose things up by accidental ordering challenges) is something like:

```c#
// Using /my-metrics as the endpoint to illustrate we want control over that AND the port.
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001 && ctx.Request.Path == "/my-metrics",
  b => b.UseMiddleware<PrometheusExporterMiddleware>());
```

The challenge is that there's no way right now to configure the location the middleware is on without doing that through `PrometheusExporterOptions`. But I _also_ need that value in the `MapWhen`. So I end up with redundant configuration.

```c#
// In ConfigureServices I need to set the options...
services.AddOptions<PrometheusExporterOptions>()
  .Configure(opt =>
  {
    opt.StartHttpListener = false;
    opt.ScrapeEndpointPath = "/my-metrics"
  });

// ...but I also need that same value in the MapWhen
app.UseHealthCheck(5001, "/healthz");
app.UseReadinessCheck(5001, "/readiness");
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001 && ctx.Request.Path == "/my-metrics",
  b => b.UseOpenTelemetryPrometheusScrapingEndpoint());
```

Having to put it in two spots like that is a recipe for "why didn't this work?" challenges for some folks who are maybe less diligent about details or who may put a typo in there or forget about having to make them match.

Separating the middleware from the endpoint configuration is important to have the control. If all `UseOpenTelemetryPrometheusScrapingEndpoint` did was add the middleware but _not_ specify the endpoint, I'd be golden.

This reminds me a bit of an issue we faced a while back with Autofac OWIN integration. [We _had_ an all-in-one mechanism](https://github.com/autofac/Autofac.Owin/blob/04476d90a2d7a73782146f5d840218861dfe37ff/src/Autofac.Integration.Owin/AutofacAppBuilderExtensions.cs#L254) for setting up Autofac lifetime scopes and then running the middleware that was registered in the container. It made for a really nice API that hid a lot of the dirty details from the consumer. However, we found there were some real use cases where someone wanted the Autofac lifetime scope to be set up in one spot, then run some of their own middleware, then run [specific middleware that was registered in the container](https://github.com/autofac/Autofac.Owin/blob/04476d90a2d7a73782146f5d840218861dfe37ff/src/Autofac.Integration.Owin/AutofacAppBuilderExtensions.cs#L313), then more custom stuff, then the remaining bits from the container. It became important to provide more control over the building of the pipeline to allow for those more advanced use cases.

I feel like this is a similar situation. I get that there's a desire to sort of abstract away things behind a clean public API, but the flexibility to do the more advanced use cases like what I'm describing isn't there, or if it is, it brings with it challenges like "specify the config twice and make sure it all matches or things will be messed up."

Perhaps the answer is _another overload_ of `UseOpenTelemetryPrometheusScrapingEndpoint` like:

```c#
public static IApplicationBuilder UseOpenTelemetryPrometheusScrapingEndpoint(this IApplicationBuilder app, string path, MeterProvider meterProvider = null)
{
  if (!path.StartsWith("/"))
  {
    path = $"/{path}";
  }

  return app.Map(
    new PathString(path),
    builder => builder.UseMiddleware<PrometheusExporterMiddleware>(meterProvider ?? app.ApplicationServices.GetRequiredService<MeterProvider>()));
}
```

However, this totally _ignores_ the options that might have been configured before, which is kind of confusing, too, from an API standpoint.

Which then makes me wonder if having the options specify a location is even interesting. I guess it is if you're using the standalone listener, but when I'm building my pipeline, that's when I'm setting up my endpoint routing and middleware, and that's where I need control.

In the end, I was just trying to do the least-breaking-thing in the existing structure; but if there's opportunity to totally rethink/redesign it, maybe having different options for different "listener types" (the standalone listener, the middleware) would be good - split them up. Then take the path part of the options out when it comes to middleware and let folks configure it in the `UseOTPSE(...)` call rather than having to specify it in options. At that point, it'd probably be worth having an overload that _just adds the middleware_ and doesn't do the `app.Map` part. You could still hide the middleware but it'd give the control back to the dev.

**Comment by CodeBlanch** [comment]
@tillig I hear you! The reason we don't want to make it `public` is then we have to support it forever 🤣 Very high bar to do that!

Let me ask, why do you need to do this?

```csharp
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001 && ctx.Request.Path == "/my-metrics",
  b => b.UseOpenTelemetryPrometheusScrapingEndpoint());
```

If you made it...

```csharp
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001,
  b => b.UseOpenTelemetryPrometheusScrapingEndpoint());
```

...it would do essentially the same thing. Meaning, you don't really need to check the path in the `MapWhen` because the inner `Map` in the extension will enforce that. You would just need to make sure that is registered after your other stuff.

If you really want to specify path there, yes, duplicating the value would bug me too :smile: What if you did this?

```csharp
var prometheusExporterOptions = app.Services.GetRequiredService<IOptions<PrometheusExporterOptions>>().Value;

app.UseHealthCheck(5001, "/healthz");
app.UseReadinessCheck(5001, "/readiness");
app.MapWhen(
  ctx => ctx.Connection.LocalPort == 5001
   && ctx.Request.Path == prometheusExporterOptions.ScrapeEndpointPath,
  b => b.UseOpenTelemetryPrometheusScrapingEndpoint());
```

Doesn't look very friendly but you could move that all into an extension something like:

```csharp
public static IApplicationBuilder UseMetrics(this IApplicationBuilder app, int port)
{
   var prometheusExporterOptions = app.Services.GetRequiredService<IOptions<PrometheusExporterOptions>>().Value;

   return app.MapWhen(
     ctx => ctx.Connection.LocalPort == port
      && ctx.Request.Path == prometheusExporterOptions.ScrapeEndpointPath,
     b => b.UseOpenTelemetryPrometheusScrapingEndpoint());
}
```

I do think it is reasonable for the official extension to provide the ability to do this type of thing. Let me know your thoughts on this: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3029

**Comment by tillig** [comment]
> The reason we don't want to make it `public` is then we have to support it forever

I'm not sure how you're _not_ going to have to maintain it forever even now. I mean, I guess I could see the potential to switch it [somehow?] from middleware to a controller or something, but I also think the only reason middleware would _stop_ working or _stop_ being something you'd need to maintain in general is if ASP.NET Core itself changed in such a major way that middleware became not a thing. If that happened, it'd likely be as different as legacy ASP.NET + OWIN or WCF, in which case it's a whole new way to adapt to the pipeline anyway.

A potentially better option is sort of what I was talking about at the end of my comment, like:

First, change `PrometheusExporterOptions` to separate endpoints out.

```c#
public class PrometheusExporterOptions
{
  public int ScrapeResponseCacheDurationMilliseconds { get; set; }
}
``` 

This removes the endpoint path from options so it can be used in routing or endpoint/pipeline setup; and it lets you also separately configure the standalone HTTP listener if you want to use that. That would _also_ serve to remove the need for `StartHttpListener` entirely because you either _add it to the pipeline_ or you _don't_. Adding it implicitly means you want to start it.

Change `UseOpenTelemetryPrometheusScrapingEndpoint` to _just_ add the middleware. You could potentially have a string optional parameter if folks want to still configure it like that.

```c#
// Control to use MapWhen or do what you want if you need it...
app.Map("/metrics", b => b.UseOpenTelemetryPrometheusScrapingEndpoint());

// ...or use the one-liner.
app.UseOpenTelemetryPrometheusScrapingEndpoint("/metrics");
```

Maybe it's two different named methods? Unclear. Point being, the options don't have the endpoint info in them anymore and you can control it a bit more during pipeline definition.

If you still want to use a standalone HTTP listener, maybe instead of having that "baked into" the `PrometheusExporter` directly, that's something you add explicitly.

```c#
using var meterProvider = Sdk.CreateMeterProviderBuilder()
  .AddMeter("MyCompany.MyProduct.MyLibrary")
  .AddPrometheusExporterWithListener("http://localhost:1234/metrics")
  .Build();
```

I mean, it could be an overload, too, where the listener is implicitly started if you pass that URL.

```c#
using var meterProvider = Sdk.CreateMeterProviderBuilder()
  .AddMeter("MyCompany.MyProduct.MyLibrary")
  .AddPrometheusExporter(endpoint: "http://localhost:1234/metrics")
  .Build();
```

Again, point there is it's explicit and not tied to the exporter itself.

Anyway, that would split out:

- Endpoint control from exporter options
- Standalone listener from pipeline listener

... and it'd give the control needed for the pipeline without exposing the middleware directly.

**Comment by CodeBlanch** [comment]
@tillig I just replied on the other PR about some of the use cases I think we should build for and why having `PrometheusExporterOptions.ScrapeEndpointPath` is useful.

As far as what to do with `HttpListenerPrefixes` and the listener, I think we are open to anything 😄 It is something @reyang and I have discussed. We have considered moving it to its own project. I like the idea of having a dedicated extension for it. Might be hard to make it config-driven with an extension. Might not be a concern. I feel like we are close on the middleware registration extension, could we try to nail that down and then we can tackle the dedicated listener stuff?

**Comment by tillig** [comment]
With #3029 coming in, I don't think we'll need this anymore. There should be enough control to do what needs to be done with the new extensions; or, if not, we can build on that.

**Pull request closed without merging**
