### PR TITLE
[repo] Add Raj as approver

### PR DESCRIPTION
**Pull request by CodeBlanch**
@rajkumar-rangaraj has been active in the OpenTelemetry .NET community and AppInsights community for a long time. He is a maintainer on the https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation repo, works on the [AzureMonitor](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor) components, and has years of experience in telemetry working on [AppInsights](https://github.com/microsoft/ApplicationInsights-dotnet/commits/main/?author=rajkumar-rangaraj). I am proposing @rajkumar-rangaraj for the approver role because he has made many [direct contributions](https://github.com/open-telemetry/opentelemetry-dotnet/pulls?q=is%3Apr+author%3Arajkumar-rangaraj+is%3Aclosed) to the repo but also he brings a lot of knowledge, wisdom, and experience into discussions which will benefit the review process.

### CODE REVIEW

**Comment by reyang** [comment]
> ... I am proposing @rajkumar-rangaraj for the approver role because he has made many direct contributions to the repo ...

@CodeBlanch can you provide a link to these contributions?

**Comment by CodeBlanch** [comment]
@reyang Description updated to include link to closed PRs for "direct contributions" mention.

**Comment by reyang** [comment]
> @reyang Description updated to include link to closed PRs for "direct contributions" mention.

I have a hard time trying to udnerstand what does "many" mean:

https://github.com/open-telemetry/opentelemetry-dotnet/graphs/contributors

image

**Review by reyang — CHANGES_REQUESTED** [review]
It's unclear what's the criteria and how is that aligned with https://github.com/open-telemetry/community/blob/main/community-membership.md#approver.

**Comment by CodeBlanch** [comment]
Which requirement are you referring to? This one?

> Reviewer for or author of at least 10 substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls).

There is an "OR" there. Raj has made direct contributions, contributed reviews on many other contributions, and routinely joins the SIG to participate in discussion and live reviews when we look at open PRs. I have no issue passing him on this requirement whatsoever 👍

There are the areas I feel @rajkumar-rangaraj will greatly excel:

* Demonstrate sound technical judgement
* Responsible for project quality control via code reviews
  * Focus on holistic acceptance of contribution such as dependencies with other features, backwards / forwards compatibility, API and flag definitions, etc
* Mentor contributors and reviewers

**Comment by reyang** [comment]
> Which requirement are you referring to? This one?
> 
> > Reviewer for or author of at least 10 substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls).
> 
> There is an "OR" there. Raj has made direct contributions, contributed reviews on many other contributions, and routinely joins the SIG to participate in discussion and live reviews when we look at open PRs. I have no issue passing him on this requirement whatsoever 👍

I understand the "OR" part, would you provide the list of PRs?

**Comment by cijothomas** [comment]
> He is a maintainer on the https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation repo, works on the [AzureMonitor](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor) components, and has years of experience in telemetry working on [AppInsights](https://github.com/microsoft/ApplicationInsights-dotnet/commits/main/?author=rajkumar-rangaraj).

While experience in related space is definitely helpful, I won't include that as a criterion for approver/maintainer in this repo. I'd suggest to see more active involvement (code reviews + code contributions) in this repo before adding as approver.

**Pull request closed without merging**
