### PR TITLE
[docs] Adjust filtering processor guidance

### PR DESCRIPTION
**Pull request by CodeBlanch**
The previous "FilteringProcessor" example required manually constructing the exporter and passing it into the processor. Many exporters do not have a public ctor so it is not possible to construct them.

## Changes

Switched the example to toggle `Activity.Recorded` instead. This works because [BatchActivityExportProcessor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d954c5bae876d114867dc99dbc8c5c5ebd92c3b1/src/OpenTelemetry/Trace/BatchActivityExportProcessor.cs#L43-L46) and [SimpleActivityExportProcessor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d954c5bae876d114867dc99dbc8c5c5ebd92c3b1/src/OpenTelemetry/Trace/SimpleActivityExportProcessor.cs#L33-L36) both no-op for this case.

### CODE REVIEW

**Review by vishweshbankwar — APPROVED** [review]

**Comment by vishweshbankwar** [comment]
@CodeBlanch - Filter by setting `activity.IsAllDataRequested = false` during OnStart. Should we document that as well?. (That will prevent all exporters to export it).

**Comment by CodeBlanch** [comment]
@vishweshbankwar Customer wants to filter based on some data on the `Activity`. Duration for example. OnEnd is really the most general-purpose spot we have to filter where all the data will be available. We could also have an OnStart example which uses `IsAllDataRequested` but more to document there to explain the limited dataset. My concern would be having both might be confusing. @cijothomas How you feel about it?

**Comment by cijothomas** [comment]
We should be only showing the OnEnd based filter as shown in this PR. There is not much value in showing Filter based on OnStart(), as Sampler is a better fit there. OnEnd is more like "tail" based filtering, based on data *not* available at SpanStart/Sample time.

**Review by cijothomas — APPROVED** [review]
LGTM

**Pull request merged**
