### PR TITLE
Extend TracerBuilder to facilitate ITracer interception

### PR DESCRIPTION
**Pull request by pcwiese**
Background:
When the active Span changes, I want to be notified and do something
with the current SpanContext. One way I can see to do that is to intercept
calls to ITracer::WithSpan (or whatever ITracer method(s) are used to activate a Span).

However, the only way to get an instance of ITracer is through the TracerFactory.
I am proposing that we add a new option to TracerBuilder where people can specify
a Func<ITracer, ITracer> that if specified is invoked for all returned ITracers.

This will allow me to create a proxy ITracer implementation and intercept every call.

usage is:
```csharp

services.AddOpenTelemetry(builder =>
{
    builder
        .SetTracerConstructionInterceptor(t => new TracerProxy(t));
});
```

Absolutely open to other suggestions to get what I need here.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Wouldn't `SpanProcessor` achieve this? It has OnBegin callback. What am I missing?

**Comment by pcwiese** [comment]
> Wouldn't `SpanProcessor` achieve this? It has OnBegin callback. What am I missing?

A couple of things come to mind here:
- A SpanProcessor only runs if the Span is being sampled, which is different from telling me when the active Span changes.
- The SpanContext is currently set AFTER the SpanProcessor runs. I want/need access to the SpanContext that belongs to the Span
- The SpanProcessor will run even if the Span isn't active/activated yet.

Also, I do think there is some value in giving people _some_ way to intercept all calls to ITracer regardless.

**Comment by SergeyKanzhelev** [comment]
Another question - is it different from overriding the entire TracerFactory and just proxy back to the original?

I'm trying to find a way to minimize the number of extensibility points needed. I see how this scenario of updating SpanContext is valuable

**Comment by pcwiese** [comment]
TracerFactory isn't overridable as is. There is no protected ctor. 
And even if it were, the library guidelines say to get a ITracer via TracerFactory, which means I we have to keep the TracerFactory as the point of entry. This is particularly true for non DI scenarios. For DI scenarios, that would probably work, but then mixed use of DI and non DI TracerFactory stuff would collide. This could possibly be solved by disallowing the use of TracerFactory directly and instead get an instance of that from some other global registry/singleton.

**Comment by SergeyKanzhelev** [comment]
> My particular scenario is to take that active SpanContext and serialize it / send it out of band to an eventing pipeline where I can create child Spans using that SpanContext at some point in the future.

So you want to record an active SpanContext on every span creation independently from the sampling? And you still want a regular pipeline of sampling, processors and exporter work?

BTW, similar thing proposed here: https://github.com/open-telemetry/oteps/pull/58 but with the different approach.

**Comment by pcwiese** [comment]
I'm going to close this review for now. It feels like a hack, even though it isn't a big change

**Comment by SergeyKanzhelev** [comment]
@pcwiese please keep posted on your scenario and how you implemented it. I'm very curious on how do you use this data.

**Pull request closed without merging**
