### PR TITLE
Update Metrics Benchmarks

### PR DESCRIPTION
**Pull request by utpilla**
## Changes
- Add benchmarks for using `TagList`

Using `TagList` starts to show its benefits when you have more than three labels as there is no allocation which makes up for the higher execution time.

Here are the benchmark results:

// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19043
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=6.0.100-rc.1.21458.32
  [Host]     : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
  DefaultJob : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT

|                                Method | WithSDK |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------------- |-------- |----------:|---------:|---------:|-------:|------:|------:|----------:|
|                        CounterHotPath |   False |  13.16 ns | 0.026 ns | 0.024 ns |      - |     - |     - |         - |
|             CounterWith1LabelsHotPath |   False |  19.27 ns | 0.279 ns | 0.261 ns |      - |     - |     - |         - |
|             CounterWith3LabelsHotPath |   False |  53.62 ns | 0.045 ns | 0.040 ns |      - |     - |     - |         - |
|             CounterWith5LabelsHotPath |   False |  81.74 ns | 0.376 ns | 0.352 ns | 0.0166 |     - |     - |     104 B |
|             CounterWith6LabelsHotPath |   False |  94.89 ns | 0.239 ns | 0.212 ns | 0.0191 |     - |     - |     120 B |
|             CounterWith7LabelsHotPath |   False | 106.70 ns | 0.306 ns | 0.255 ns | 0.0216 |     - |     - |     136 B |
| **CounterWith1LabelsHotPathUsingTagList** |   False |  **50.93 ns** | 0.113 ns | 0.101 ns |      - |     - |     - |         - |
| **CounterWith3LabelsHotPathUsingTagList** |   False |  **85.60 ns** | 0.079 ns | 0.066 ns |      - |     - |     - |         - |
| **CounterWith5LabelsHotPathUsingTagList** |   False | **128.40 ns** | 0.231 ns | 0.180 ns |      - |     - |     - |         - |
| **CounterWith6LabelsHotPathUsingTagList** |   False | **147.48 ns** | 0.139 ns | 0.123 ns |      - |     - |     - |         - |
| **CounterWith7LabelsHotPathUsingTagList** |   False | **161.00 ns** | 0.436 ns | 0.408 ns |      - |     - |     - |         - |

|                                Method | WithSDK |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------------- |-------- |----------:|---------:|---------:|-------:|------:|------:|----------:|
|                        CounterHotPath |    True |  39.14 ns | 0.027 ns | 0.026 ns |      - |     - |     - |         - |
|             CounterWith1LabelsHotPath |    True | 103.26 ns | 0.088 ns | 0.082 ns |      - |     - |     - |         - |
|             CounterWith3LabelsHotPath |    True | 434.06 ns | 0.249 ns | 0.195 ns |      - |     - |     - |         - |
|             CounterWith5LabelsHotPath |    True | 602.86 ns | 2.299 ns | 2.151 ns | 0.0362 |     - |     - |     232 B |
|             CounterWith6LabelsHotPath |    True | 704.22 ns | 2.053 ns | 1.603 ns | 0.0420 |     - |     - |     264 B |
|             CounterWith7LabelsHotPath |    True | 807.64 ns | 2.149 ns | 1.905 ns | 0.0467 |     - |     - |     296 B |
| **CounterWith1LabelsHotPathUsingTagList** |    True | **140.95 ns** | 0.069 ns | 0.065 ns |      - |     - |     - |         - |
| **CounterWith3LabelsHotPathUsingTagList** |    True | **464.09 ns** | 1.805 ns | 1.688 ns |      - |     - |     - |         - |
| **CounterWith5LabelsHotPathUsingTagList** |    True | **644.18 ns** | 1.354 ns | 1.200 ns | 0.0200 |     - |     - |     **128 B** |
| **CounterWith6LabelsHotPathUsingTagList** |    True | **747.60 ns** | 1.711 ns | 1.517 ns | 0.0229 |     - |     - |     **144 B** |
| **CounterWith7LabelsHotPathUsingTagList** |    True | **858.42 ns** | 1.486 ns | 1.390 ns | 0.0248 |     - |     - |     **160 B** |

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by pellared** [comment]
Shouldn't the comment above the `namespace Benchmarks.Metrics` be updated? As it contains the latest benchmark result.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2420 - need to merge this and re-run benchmarks.

**Comment by utpilla** [comment]
> #2420 - need to merge this and re-run benchmarks.

Here are the new results:

// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19043
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=6.0.100-rc.1.21458.32
  [Host]     : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
  DefaultJob : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT


|                                Method | WithSDK |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------------- |-------- |----------:|---------:|---------:|-------:|------:|------:|----------:|
|                        CounterHotPath |   False |  12.87 ns | 0.086 ns | 0.080 ns |      - |     - |     - |         - |
|             CounterWith1LabelsHotPath |   False |  19.36 ns | 0.083 ns | 0.069 ns |      - |     - |     - |         - |
|             CounterWith3LabelsHotPath |   False |  53.71 ns | 0.336 ns | 0.314 ns |      - |     - |     - |         - |
|             CounterWith5LabelsHotPath |   False |  79.82 ns | 0.525 ns | 0.439 ns | 0.0166 |     - |     - |     104 B |
|             CounterWith6LabelsHotPath |   False |  91.35 ns | 0.827 ns | 0.733 ns | 0.0191 |     - |     - |     120 B |
|             CounterWith7LabelsHotPath |   False | 104.40 ns | 0.924 ns | 0.865 ns | 0.0216 |     - |     - |     136 B |
| **CounterWith1LabelsHotPathUsingTagList** |   False |  **50.43 ns** | 0.415 ns | 0.388 ns |      - |     - |     - |         - |
| **CounterWith3LabelsHotPathUsingTagList** |   False |  **88.48 ns** | 0.402 ns | 0.376 ns |      - |     - |     - |         - |
| **CounterWith5LabelsHotPathUsingTagList** |   False | **121.61 ns** | 0.472 ns | 0.418 ns |      - |     - |     - |         - |
| **CounterWith6LabelsHotPathUsingTagList** |   False | **139.11 ns** | 0.593 ns | 0.554 ns |      - |     - |     - |         - |
| **CounterWith7LabelsHotPathUsingTagList** |   False | **154.07 ns** | 0.773 ns | 0.685 ns |      - |     - |     - |         - |
|                        CounterHotPath |    True |  38.23 ns | 0.235 ns | 0.220 ns |      - |     - |     - |         - |
|             CounterWith1LabelsHotPath |    True | 102.48 ns | 0.942 ns | 0.881 ns |      - |     - |     - |         - |
|             CounterWith3LabelsHotPath |    True | 417.00 ns | 2.904 ns | 2.716 ns |      - |     - |     - |         - |
|             CounterWith5LabelsHotPath |    True | 578.45 ns | 5.287 ns | 4.946 ns | 0.0162 |     - |     - |     104 B |
|             CounterWith6LabelsHotPath |    True | 665.56 ns | 3.716 ns | 3.476 ns | 0.0191 |     - |     - |     120 B |
|             CounterWith7LabelsHotPath |    True | 778.88 ns | 5.482 ns | 4.578 ns | 0.0210 |     - |     - |     136 B |
| **CounterWith1LabelsHotPathUsingTagList** |    True | **135.55 ns** | 1.012 ns | 0.947 ns |      - |     - |     - |         - |
| **CounterWith3LabelsHotPathUsingTagList** |    True | **457.96 ns** | 4.242 ns | 3.968 ns |      - |     - |     - |         - |
| **CounterWith5LabelsHotPathUsingTagList** |    True | **631.81 ns** | 3.423 ns | 2.858 ns |      - |     - |     - |         - |
| **CounterWith6LabelsHotPathUsingTagList** |    True | **719.81 ns** | 4.704 ns | 4.400 ns |      - |     - |     - |         - |
| **CounterWith7LabelsHotPathUsingTagList** |    True | **828.88 ns** | 4.321 ns | 3.830 ns |      - |     - |     - |         - |

**Comment by cijothomas** [comment]
We should be recommending TagList *only* if there are more than 3 tags. Otherwise use other overloads which is faster.

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
> We should be recommending TagList _only_ if there are more than 3 tags. Otherwise use other overloads which is faster.

@CodeBlanch Tagging you here, as per offline conversation, to see if this slowness is due to the copy of each KVP to form the taglist.

**Comment by reyang** [comment]
> > We should be recommending TagList _only_ if there are more than 3 tags. Otherwise use other overloads which is faster.
> 
> @CodeBlanch Tagging you here, as per offline conversation, to see if this slowness is due to the copy of each KVP to form the taglist.

Trying to clarify it in #5243.

**Pull request merged**
