### PR TITLE
Address AOT warnings in Exporter.OpenTelemetryProtocol

### LINKED ISSUE #3429: OpenTelemetry .NET SDK is not AOT safe
# Bug Report

When publishing my app with `dotnet publish --self-contained -p:PublishAot=true -r win-x64 -o out` and then running it, the app crashes on startup with an open telemetry stack:

```
Unhandled Exception: System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.Reflection.MissingMetadataException: 'OpenTelemetry.Context.AsyncLocalRuntimeContextSlot<System.Int32>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
   at System.Reflection.Runtime.General.TypeUnifier.WithVerifiedTypeHandle(RuntimeConstructedGenericTypeInfo, RuntimeTypeInfo[]) + 0x15a
   at System.Reflection.Runtime.General.TypeUnifier.GetConstructedGenericTypeWithTypeHandle(RuntimeTypeInfo, RuntimeTypeInfo[]) + 0x3b
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.MakeGenericType(Type[]) + 0x40d
   at OpenTelemetry.Context.RuntimeContext.RegisterSlot[T](String) + 0x161
   at OpenTelemetry.SuppressInstrumentationScope..cctor() + 0x1d
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x16a
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x26b
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0x1c
   at OpenTelemetry.SuppressInstrumentationScope.get_IsSuppressed() + 0x1b
   at OpenTelemetry.Sdk.get_SuppressInstrumentation() + 0x15
   at OpenTelemetry.Logs.OpenTelemetryLoggerProvider..cctor() + 0x10
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x16a
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x26b
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x1c
   at OpenTelemetry.Logs.OpenTelemetryLoggerProvider..ctor(IOptionsMonitor`1) + 0x29
```

libraries:

```
    <PackageReference Update="OpenTelemetry" Version="[1.2.0-rc3]" />
    <PackageReference Update="OpenTelemetry.Api" Version="[1.2.0-rc3]" />
    <PackageReference Update="OpenTelemetry.Exporter.Console" Version="[1.2.0-rc3]" />
    <PackageReference Update="OpenTelemetry.Exporter.Prometheus" Version="[1.2.0-rc3]" />
```

more information: https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot

### PR DESCRIPTION
**Pull request by eerhardt**
This addresses the AOT warnings in the last library in opentelemetry-dotnet.

1. Google.Protobuf v3.19.4 isn't trimming and AOT compatible. We need to upgrade to a newer version. I chose the latest patch in v3.22.x. v3.22.0 was the first version that is AOT compatible.

2. There were 2 places in Exporter.OpenTelemetryProtocol that was using System.Reflection.Emit to set a private field on Protobuf's RepeatedField class in order to return it to a pool. Setting this private field is no longer necessary since v3.22.0 because the Clear method was updated to support this scenario. See https://github.com/protocolbuffers/protobuf/commit/a4fd21618635b891fefe34d5e440d6d9464e659f

Fix #3429 

@vitek-karas @Yun-Ting @reyang @utpilla

### CODE REVIEW

**Comment by eerhardt** [comment]
@CodeBlanch - I see you commented on the Google.Protobuf [issue](https://github.com/protocolbuffers/protobuf/issues/7828) and [PR](https://github.com/protocolbuffers/protobuf/pull/10508) that fixed the `Clear()` method to allow for pooling. Was there a reason OTel hasn't already updated to use this method instead of using Ref.Emit?

**Review by reyang — APPROVED** [review]
LGTM with a changelog entry.

**Comment by Yun-Ting** [comment]
> @CodeBlanch - I see you commented on the Google.Protobuf [issue](https://github.com/protocolbuffers/protobuf/issues/7828) and [PR](https://github.com/protocolbuffers/protobuf/pull/10508) that fixed the `Clear()` method to allow for pooling. Was there a reason OTel hasn't already updated to use this method instead of using Ref.Emit?

+1 on curious about what happened to the above change.
And a minor thing - [this](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7cb92d3b6dbad169048e5aa07939ef613f2587e2/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj#L22C1-L22C115) reference can be removed along with this change.

**Comment by utpilla** [comment]
> @CodeBlanch - I see you commented on the Google.Protobuf [issue](https://github.com/protocolbuffers/protobuf/issues/7828) and [PR](https://github.com/protocolbuffers/protobuf/pull/10508) that fixed the `Clear()` method to allow for pooling. Was there a reason OTel hasn't already updated to use this method instead of using Ref.Emit?

@eerhardt @Yun-Ting  We had updated this package version earlier but had to revert the changes in #4407. The reason behind it was mainly to not affect any auto-instrumentation users who could be using a lower version of the package. Auto-instrumentation dynamically loads this package and its dependencies. Check this [comment]( https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2220#issuecomment-1493920083).

Back then we didn't have any immediate need to be AOT-safe. However, AOT-safety is the major feature to be offered in `1.7.0` so updating this package version is much needed.

**Review by utpilla — APPROVED** [review]

**Comment by Kielek** [comment]
@eerhardt, please check this PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/4201

You should be able to drop  reference to `System.Reflection.Emit.Lightweight` in src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj.

The reason to keep older version is AutoInstrumentation (it will narrow the set of application which can be handled without code changes).

**Review by pjanotti — APPROVED** [review]

**Comment by Yun-Ting** [comment]
> > @CodeBlanch - I see you commented on the Google.Protobuf [issue](https://github.com/protocolbuffers/protobuf/issues/7828) and [PR](https://github.com/protocolbuffers/protobuf/pull/10508) that fixed the `Clear()` method to allow for pooling. Was there a reason OTel hasn't already updated to use this method instead of using Ref.Emit?
> 
> @eerhardt @Yun-Ting We had updated this package version earlier but had to revert the changes in #4407. The reason behind it was mainly to not affect any auto-instrumentation users who could be using a lower version of the package. Auto-instrumentation dynamically loads this assembly and its dependencies. Check this [comment](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2220#issuecomment-1493920083).
> 
> Back then we didn't have any immediate need to be AOT-safe. However, AOT-safety is the major feature to be offered in `1.7.0` so updating this package version is much needed.

Thank you @utpilla for sharing this!

**Review by Yun-Ting — APPROVED** [review]
LGTM assuming this comment got addressed: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4859#issuecomment-1724856766. Thanks!

**Review by Kielek — APPROVED** [review]

**Pull request merged**
