### PR TITLE
Refactored ConsoleExporter

### PR DESCRIPTION
**Pull request by utpilla**
## Changes
- Refactored ConsoleExporter generic class to get rid of type specific check
- Added ConsoleActivityExporter and ConsoleLogRecordExporter classes

### CODE REVIEW

**Comment by utpilla** [comment]
@CodeBlanch It'd be great if you could take a look at this and let me know of what you think? This is in regards to this discussion: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1438#discussion_r517040554

**Comment by utpilla** [comment]
@cijothomas @reyang I would love to get any suggestions for this.

**Comment by CodeBlanch** [comment]
@utpilla I like it! I think this is definitely a more standard use of generics. Could probably clean it up even further like...

```csharp
public abstract class ConsoleExporter<T> : BaseExporter<T>
{
   public override ExportResult Export(in Batch<T> batch)
   {
      foreach (var item in batch)
      {
         ExportItem(item);
      }
   }

   protected abstract void ExportItem(T item);

   protected void WriteLine(string message) { /* Existing code goes here*/ }
}

internal class ConsoleActivityExporter : ConsoleExporter<Activity>
{
   protected override void ExportItem(Activity item)
   {
      WriteLine($"Activity.Id:          {activity.Id}");
      /* Etc. */
   }
}
```

Tweaks: Made ConsoleExporter abstract, switched the action to an abstract method, and made WriteLine protected so super can call it.

**Comment by utpilla** [comment]
I have created a new PR #1593 with the suggested changes.

**Pull request closed without merging**
