### PR TITLE
Standardize Copyright Disclaimer in of all the *.cs Files

### PR DESCRIPTION
**Pull request by MeenuyD**
In alignment with OpenTelemetry practices (examples https://github.com/open-telemetry/opentelemetry-demo/blob/f44860602656e2313f3cfe6f7e42a464a341786b/src/cartservice/src/Program.cs#L1C1-L2C39 and
https://github.com/open-telemetry/opentelemetry-cpp/blob/ad626cec4598165e0d297b0bdb3880968c5dfe88/api/include/opentelemetry/config.h#L1-L2), simplified the copyright disclaimer in all *.cs files to the format:

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
This standardizes the copyright information and aligns it with our common practices across OpenTelemetry projects.
#4900

### CODE REVIEW

**Comment by utpilla** [comment]
@MeenuyD Please resolve the merge conflicts.

**Comment by utpilla** [comment]
@MeenuyD Could you please confirm if you're still planning to work on this PR?

**Comment by MeenuyD** [comment]
Yes I am am working on this

**Comment by MeenuyD** [comment]
I have changed all the .cs file copyright can you please review

**Comment by reyang** [comment]
> I have changed all the .cs file copyright can you please review

Could you resolve the merge conflicts?

image

**Comment by MeenuyD** [comment]
Hello @reyang can you please guide how can resolve these conflicts

**Review by alanwest — CHANGES_REQUESTED** [review]
@MeenuyD I resolved the conflicts on your branch. You will need to pull latest.

For future reference, read up on merge conflicts and how to resolve them: https://docs.github.com/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

There are still quite a few files that still have the old copyright header. These need to be fixed.

**Pull request closed without merging**
