### PR TITLE
Renaming TraceContextFormat/B3Format/BaggageFormat

### PR DESCRIPTION
**Pull request by eddynaka**
Refs #1143

## Changes
- Renaming TraceContextFormat to TextMapPropagator
- B3Format to B3Propagator
- BaggageFormat to BaggagePropagator

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by eddynaka** [comment]
Today we have 4 classes that implements `ITextFormat`: `B3Format`, `BaggageFormat`, `CompositePropagator`, `TextMapPropagator`.

Should we rename `B3Format` and `BaggageFormat` to `B3Propagator` and `BaggagePropagator`?

**Comment by CodeBlanch** [comment]
> Should we rename B3Format and BaggageFormat to B3Propagator and BaggagePropagator?

I like it!

**Comment by CodeBlanch** [comment]
Not on this PR, but maybe we should rename `ITextFormat` -> `IPropagator`?

**Comment by eddynaka** [comment]
> Not on this PR, but maybe we should rename `ITextFormat` -> `IPropagator`?

i would like that as well! lets finish this and do that next! :)

**Pull request merged**
