### PR TITLE
Make ITracer an abstract class and rename to Tracer

### PR DESCRIPTION
**Pull request by lmolkova**
Tracer in SDK becomes `TracerSdk` (which is internal class).

This allows Tracer abstraction to be extendable.

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
LGTM :+1:

Only suggest would be to use `TracerSDK` for SDK implementation to be consistent with Metrics classes:
[MeterSDK](https://github.com/open-telemetry/opentelemetry-dotnet/blob/fac2fba3db5d0b89b4766779ad542b80c1f953ec/src/OpenTelemetry/Metrics/MeterSDK.cs)
[CounterSDK](https://github.com/open-telemetry/opentelemetry-dotnet/blob/fac2fba3db5d0b89b4766779ad542b80c1f953ec/src/OpenTelemetry/Metrics/CounterSDK.cs)

(Or rename the metrics classes to use `Sdk`)

**Comment by lmolkova** [comment]
@MikeGoldsmith good point. I'll rename metrics and counter to Sdk according to .NET naming conventions

**Comment by lmolkova** [comment]
@SergeyKanzhelev can you approve so I can merge?

**Comment by whihathac** [comment]
What's the reasoning behind making an Interface into an abstract class?

**Comment by MikeGoldsmith** [comment]
An abstract class can provide default functionality for added methods so is backward compatible with existing implementations. Adding methods to an interface is a breaking change.

**Pull request merged**
