### PR TITLE
Move common Prometheus exporter tests to their own project

### PR DESCRIPTION
**Pull request by alanwest**
Moved `PrometheusSerializerTests.cs` and `PrometheusCollectionManagerTests.cs` to a common test project.

`PrometheusSerializerTests.cs` used to be in the HttpListener test project. This meant these tests could not be run in a non-Windows development environment. Also, this meant the CI was only running them for the `net462` target.

`PrometheusCollectionManagerTests.cs` used to be in the AspNetCore test project. The CI was only running them for the `net6.0` target.

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by reyang — APPROVED** [review]
LGTM.

**Comment by alanwest** [comment]
Failing test (maybe flaky? maybe a legit bug?). This test used to succeed against the net462, but two failures in a row. I suppose it's possible a bug was introduced in the work to split up the packages.

I'm happy to investigate, but would like to address in a separate PR. My main goal for this PR was to get it landed so I can add some Prometheus tests for the new UpDownCounter support in #3606. Adding a skip for net462 for now.

```
[xUnit.net 00:00:46.17]     OpenTelemetry.Exporter.Prometheus.Tests.PrometheusCollectionManagerTests.EnterExitCollectTest [FAIL]
[xUnit.net 00:00:46.17]       Assert.Equal() Failure
[xUnit.net 00:00:46.17]       Expected: 1
[xUnit.net 00:00:46.17]       Actual:   2
[xUnit.net 00:00:46.18]       Stack Trace:
[xUnit.net 00:00:46.18]         test\OpenTelemetry.Exporter.Prometheus.Tests\PrometheusCollectionManagerTests.cs(107,0): at OpenTelemetry.Exporter.Prometheus.Tests.PrometheusCollectionManagerTests.<EnterExitCollectTest>d__0.MoveNext()
[xUnit.net 00:00:46.18]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:46.18]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:46.18]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:46.18]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:46.18]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:46.18]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:46.18]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:46.18]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Review by TimothyMothra — APPROVED** [review]
LGTM.

Looks like a Prometheus test failed:

>   Failed OpenTelemetry.Exporter.Prometheus.Tests.PrometheusCollectionManagerTests.EnterExitCollectTest [10 s]

Is this related to your changes or a new flaky test?

**Comment by alanwest** [comment]
> Is this related to your changes or a new flaky test?

It's related in that it's now built against `net462` again with this PR, but the test is not new. It used to be built against `net462` and was presumably passing at one point in time. I'll open a draft PR right after this removing the skip and follow on with troubleshooting. The problem was not immediately apparent to me. Might need to boot up a Windows machine and take a looksie.

**Review by utpilla — APPROVED** [review]

**Pull request merged**
