### PR TITLE
Remove ILogger scope from the ASP.NET Core logging getting started doc

### PR DESCRIPTION
**Pull request by reyang**
ILogger scope has introduced some confusion to folks who just want to get started.
This PR makes the getting-started doc simpler and cleaner.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Comment by noahfalk** [comment]
This looks fine to me. 

fyi @davidfowl.

**Comment by davidfowl** [comment]
Why did we remove that?

This is what the aspire default template has:

```C#
builder.Logging.AddOpenTelemetry(logging =>
{
    logging.IncludeFormattedMessage = true;
    logging.IncludeScopes = true;
});

```

**Comment by noahfalk** [comment]
Because it appears log a bunch of redundant data that OTel already knows how to capture. Do you believe there something important enough in there that it needs to be enabled by default?

**Comment by davidfowl** [comment]
>  Do you believe there something important enough in there that it needs to be enabled by default?

Yes, it going to stay the default in aspire.

I don't see any duplication in the aspire dashboard (OTLP endpoint). Maybe its a specific kind of app?

**Comment by cijothomas** [comment]
Here's the output from the [getting-started app](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/getting-started-aspnetcore):

```txt
LogRecord.Timestamp:               2024-01-26T15:30:00.2604163Z
LogRecord.TraceId:                 7d63ba8a20f49c10982c966624c3bbf3
LogRecord.SpanId:                  fd093be1dff74bcf
LogRecord.TraceFlags:              None
LogRecord.CategoryName:            Program
LogRecord.Severity:                Info
LogRecord.SeverityText:            Information
LogRecord.Body:                    Food `{name}` price changed to `{price}`.
LogRecord.Attributes (Key:Value):
    name: artichoke
    price: 9.99
    OriginalFormat (a.k.a Body): Food `{name}` price changed to `{price}`.
LogRecord.EventId:                 344095174
LogRecord.EventName:               FoodPriceChanged
LogRecord.ScopeValues (Key:Value):
[Scope.0]:SpanId: fd093be1dff74bcf
[Scope.0]:TraceId: 7d63ba8a20f49c10982c966624c3bbf3
[Scope.0]:ParentId: 0000000000000000
[Scope.1]:ConnectionId: 0HN0UGEKB9KAE
[Scope.2]:RequestId: 0HN0UGEKB9KAE:00000001
[Scope.2]:RequestPath: /
```

Scopes are duplicating the spanid,traceid.  And other attributes as well coming from asp.net components, which user may not want.

**Comment by davidfowl** [comment]
Is this specific to how the console log exporter in OTEL outputs the scopes?

**Comment by cijothomas** [comment]
> Is this specific to how the console log exporter in OTEL outputs the scopes?

No. OTLP Exporter would have the same. (Only thing specific to console exporter is it prefixes "scope-depth", which is not done by OTLP Exporter)

**Comment by davidfowl** [comment]
I think this is fine to leave out in this sample but aspire is leaving it in 😄

**Pull request merged**
