### PR TITLE
[api] Add Baggage.Attach API

### LINKED ISSUE #3257: Baggage.Current gets shared/overwritten when running multiple parallel tasks?
My scenario is similar to the RabbitMQ microservice example (https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/MicroserviceExample) We have a backend service/receiver that keeps checking an Azure queue for messages in batches of 10 and it starts execution for each such message in parallel via Parallel.ForEach. These messages are submitted from a frontend service/sender and each such message within it contains our logging context which I'm now setting into Baggage.Current by writing a custom Propagator that injects/extracts our logging context into Baggage.Current. So the pseudo code for the above looks like:

```
// Receiver/backend logic
WorkflowSchedulerAsync()
{
    Baggage defaultBaggage = Baggage.Create();
    while (!stopRequested)
    {
         list<Message> messages = await getFromAzureQueue();
         if (messages.any())
        {
              // Start some work in parallel and pick some more work
              Parallel.Foreach(messages, async m => await ProcessMessage(m)(;
        }
        
       Baggage.Current = defaultBaggage;    <<< 1. Will this interfere with 2. below?
    }
}

async Task ProcessMessage(Message m)
{
    var parentContext = propagator.Extract(default, m.CarrierPayload, SomeMethodToExtractContextFromCarrier(...))
    Baggage.Current = parentContext.Baggage; << 2. Will doProcessing below running for a message m1 
        see the Current value being overwritten due to this line whenever ProcessMessageAsync gets
        invoked again in parallel for a new message m2?

    // Expect above baggage to be available w/o interference.
    await DoProcessing(m);
}
```

1. What I'm seeing is that while DoProcessing() is running if 1. executes then code within DoProcessing no longer sees the baggage values set via 2.
2. If I comment out 1. still parallel runs of DoProcessing() for different messages end up sharing the same "Current".
3. If I comment out 1. then after one iteration of the loop that kicked of some message processing then the second iteration of the loop sees Baggage.Current to be what was set last by ProcessMessage. 

I looked at the Baggage implementation and it is based on AsyncLocal but one thing I noticed is that the Baggage has a [EnsureBaggageHolder](https://github.com/open-telemetry/opentelemetry-dotnet/blob/95500ff8fa025a357a5c7d4d4e0f6b7c03b7cdbd/src/OpenTelemetry.Api/Baggage.cs#L368) method which ensures that the holder is only allocated once and manipulating Current ends up adding/removing a reference to the Baggage maintained in this holder. So all tasks running in parallel will access the same BaggerHolder instance (which is like a singleton) and thus end up sharing the BaggerHolder.Baggage reference. So Baggage.Current updates from tasks running in parallel can interfere with each other.

Our custom library also uses a static AsyncLocal<OurCustomContext> context = new AsyncLocal<OurCustomContext> and ProcessMessage() updates context.Value with new instances of CustomContext that are coming in the message. And each parallel task that is running sees their own CustomContext as value in the static AsyncLocal keeps getting replaced (its used as a value, not as a reference to value).

So could someone explain what is expected here? Have I misunderstood this completely or this could be a bug? I was expecting AsyncLocal semantics ie outer methods don't see changes made to Current by inner methods and N parallel tasks processing N messages can modify their Baggage.Current w/o affecting other tasks Baggage.Current values. Otherwise I'm at a loss how to use Baggage.Current correctly.

FYI, I'm using nuget package version 1.2.

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #3257
Alternative design #5208

[Note: The "attach" name is taken from [Otel Specification > Context > Optional Global operations](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/context#optional-global-operations)]

## Goals

The goal here is to introduce an API which makes the `Baggage` ambient context flow behavior explicit. The current APIs are marked as obsolete to encourage users to migrate to the new safe API but nothing has changed and nothing will break.

## Changes

* Adds nullable annotations for the Baggage API.
* Adds `Baggage.Attach` API which can be used to establish a new `Baggage` context which will flow on the current thread and across tasks until detached/disposed (`AsyncLocal` behavior).
* Obsolete existing static APIs on `Baggage` which interact with `Baggage.Current`.

## Public API Changes

```diff
public readonly struct Baggage : IEquatable<Baggage>
{
+    public static IDisposable Attach() {}
+    public static IDisposable Attach(Baggage baggage) {}
}
```

## Obsoletions

```diff
public readonly struct Baggage : IEquatable<Baggage>
{
    public static Baggage Current
    {
        get {}
+       [Obsolete(BaggageCurrentSetterObsoleteMessage)]
        set {}
    }

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static IReadOnlyDictionary<string, string> GetBaggage(Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static Dictionary<string, string>.Enumerator GetEnumerator(Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static string? GetBaggage(string name, Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static Baggage SetBaggage(string name, string? value, Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static Baggage SetBaggage(IEnumerable<KeyValuePair<string, string?>> baggageItems, Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static Baggage RemoveBaggage(string name, Baggage baggage = default) {}

+   [Obsolete(BaggageStaticMethodObsoleteMessage)]
    public static Baggage ClearBaggage(Baggage baggage = default) {}
}
```

### Simple case where user doesn't want to pass the current baggage on a specific call

```csharp
// Create a new downstream empty baggage context
using (Baggage.Attach())
{
    await AuthenticateUserAsync();
}
```

### More complex case where the user wants to fork the current baggage and add something for each call

```csharp
using var baggageScope = Baggage.Attach(Baggage.Create().SetBaggage("TenantId", "1234"));

List<Task> jobTasks = new();
foreach (var job in jobs)
{
   jobTasks.Add(LaunchJob(job));
}

await Task.WhenAll(jobTasks);

static async Task LaunchJob(Job job)
{
   // Create a new downstream baggage context from the current one with a new key added for the job
   using (Baggage.Attach(Baggage.Current.SetBaggage("JobId", job.Id)))
   {
       // Will see "TenantId" & "JobId" on Baggage
       await RunJob(job);
   }
}
```

### Setting `Baggage` for an AspNetCore request via middleware

```csharp
// Before
public class BaggageMiddleware
{
    private readonly RequestDelegate next;

    public BaggageMiddleware(RequestDelegate next)
    {
        this.next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        await this.ReadTenantIdFromDatabase();

        await this.next(context);
    }

    private async Task ReadTenantIdFromDatabase()
    {
        // Simulate async call to DB
        await Task.Yield();

        Baggage.SetBaggage("tenantId", "1234");
    }
}

// After
public class BaggageMiddleware
{
    private readonly RequestDelegate next;

    public BaggageMiddleware(RequestDelegate next)
    {
        this.next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var tenantId = await this.ReadTenantIdFromDatabase();

        using (Baggage.Attach(Baggage.Current.SetBaggage("tenantId", tenantId)))
        {
            await this.next(context);
        }
    }

    private async Task<string> ReadTenantIdFromDatabase()
    {
        // Simulate async call to DB
        await Task.Yield();

        return "1234";
    }
}
```

### Prevent `Baggage.Current` from flowing on a specific downstream call

```csharp
// Before
private async Task AuthenticateAsync()
{
    var currentBaggageContainer = RuntimeContext.GetValue("otel.baggage");

    RuntimeContext.SetValue("otel.baggage", null);

    try
    {
        await CallAuthenticationServiceAsync();
    }
    finally
    {
        RuntimeContext.SetValue("otel.baggage", currentBaggageContainer);
    }
}

// After
private async Task AuthenticateAsync()
{
    using var baggageScope = Baggage.Attach();

    await CallAuthenticationServiceAsync();
}
```

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [X] Unit tests added/updated
* [X] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by CodeBlanch** [comment]
RE: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5208#issuecomment-1892695769

@alanwest's proposed API is this:

```csharp
void Main() {
  using (var scope1 = ContextBuilder.NewContext().WithBaggage("key1", "key1").StartScope()) {
    // Baggage.Current contains key1/value1
    using (var scope2 = ContextBuilder.NewContext().WithBaggage({"key2", "value2"}).StartScope()) {
      // Baggage.Current only contains key2/value2 here.
      
      // If you also wanted key1/value1 in baggage here, then it would need to be explicit.
      // Something like:
      // var scope2 = ContextBuilder.FromContext(scope1).WithBaggage({"key2", "value2"})
      // The context of scope2 would be derived from scope1 and key2/value2 would be additive
    }
    
    // scope2 has been disposed and scope1 has been restored, and
    // Baggage.Current contains key1/value1
  }  
}
```

The API being proposed here is similar:

```csharp
void Main() {
  using (Baggage.Attach(Baggage.Create().SetBaggage("key1", "key1")) {
    // Baggage.Current contains key1/value1
    using (Baggage.Attach(Baggage.Create().SetBaggage("key2", "key2")) {
      // Baggage.Current only contains key2/value2 here.
      
      // If you also wanted key1/value1 in baggage here, then it would need to be explicit.
      // Something like:
      // var scope2 = ContextBuilder.FromContext(scope1).WithBaggage({"key2", "value2"})
      // The context of scope2 would be derived from scope1 and key2/value2 would be additive
    }
    
    // scope2 has been disposed and scope1 has been restored, and
    // Baggage.Current contains key1/value1
  }  
}
```

But with less new artifacts / smaller public API.

I think it would be great to have a fully spec-compliant "Context" API. However, we couldn't do it strictly in OTel .NET because we don't own `SpanContext` (`ActivityContext`). That is part of `System.Diagnostics.DiagnosticSource` (.NET Runtime).

My thinking is we work with .NET on what that API should be. Once .NET has that API available, we can `[Obsolete] public readonly struct Baggage` and recommend the .NET API instead.

The changes here are good IMO to make the current OTel Baggage API more safe / spec-complaint in the meantime until that is available.

**Comment by reyang** [comment]
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#operations) requires several operations (e.g. [Set Value](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#set-value), [Remove Value](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#remove-value)), how to achieve these with the proposal from this PR?

**Comment by CodeBlanch** [comment]
@reyang 

Those APIs are still there on `readonly struct Baggage`. The things being obsoleted on this PR are the static APIs which mutate the ambient context.

Here are the untouched APIs which I think are pretty spec-compliant at the moment:

```csharp
public readonly struct Baggage : IEquatable<Baggage>
{
   public int Count { get; }
   public IReadOnlyDictionary<string, string> GetBaggage() {}
   public string? GetBaggage(string name) {}
   public Baggage SetBaggage(string name, string? value) {}
   public Baggage SetBaggage(params KeyValuePair<string, string?>[] baggageItems) {}
   public Baggage SetBaggage(IEnumerable<KeyValuePair<string, string?>> baggageItems) {}
   public Baggage RemoveBaggage(string name) {}
   public Baggage ClearBaggage() {}

   // Helper for creating Baggage instances but new Baggage() or default(Baggage) work equally well
   public static Baggage Create(Dictionary<string, string>? baggageItems = null) {}

   // Ceremony stuff
   public Dictionary<string, string>.Enumerator GetEnumerator() {}
   public bool Equals(Baggage other) {}
   public override bool Equals(object? obj) {}
   public override int GetHashCode() {}
   public static bool operator ==(Baggage left, Baggage right) {}
   public static bool operator !=(Baggage left, Baggage right) {}
}
```

When it comes to working with a `Baggage` instance those methods follow the immutability rules of the spec. Meaning they always return something new, the instance invoked is never modified.

```csharp
var b1 = Baggage.Create().SetBaggage("k1, "v1");
var b2 = b1.SetBaggage("k2", "v2");
var b3 = b2.RemoveBaggage("k2").SetBaggage("k3, "v3");

// b1 has k1
// b2 has k1 & k2
// b3 has k1 & k3
```

How those work with the new API is you build up some `Baggage` and then attach it:

```csharp
var newBaggage = Baggage.Create().SetBaggage("k1", "v1");

using var scope = Baggage.Attach(newBaggage);

// Everything running under scope has Baggage.Current with "k1"
```

If you want to work off the existing `Baggage.Current`:

```csharp
var newBaggage = Baggage.Current.RemoveBaggage("k1").SetBaggage("newThing", "v1");

using var scope = Baggage.Attach(newBaggage);

// Everything running under scope has whatever was in Baggage.Current without "k1" and with "newThing"
```

**Comment by reyang** [comment]
> How those work with the new API is you build up some `Baggage` and then attach it:
> 
> ```cs
> var newBaggage = Baggage.Create().SetBaggage("k1", "v1");
> 
> using var scope = Baggage.Attach(newBaggage);
> 
> // Everything running under scope has Baggage.Current with "k1"
> ```
> 
> If you want to work off the existing `Baggage.Current`:
> 
> ```cs
> var newBaggage = Baggage.Current.RemoveBaggage("k1").SetBaggage("newThing", "v1");
> 
> using var scope = Baggage.Attach(newBaggage);
> 
> // Everything running under scope has whatever was in Baggage.Current without "k1" and with "newThing"
> ```

I still don't understand, for example, how to use this in the following situation:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/dfd27c50408e770963f9d60880c1da04810c409d/src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs#L62

**Comment by CodeBlanch** [comment]
@reyang 

> I still don't understand, for example, how to use this in the following situation:
>
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/dfd27c50408e770963f9d60880c1da04810c409d/src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs#L62

You wouldn't use the `Attach` API here.

If you are writing **outgoing instrumentation** you use `Baggage.Current` to inject _whatever_ the current `Baggage` is (may be empty):

https://github.com/open-telemetry/opentelemetry-dotnet/blob/dfd27c50408e770963f9d60880c1da04810c409d/src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs#L108-L112

**Users** who want to send some `Baggage` on a Grpc.Net call _would_ use the `Attach` API:

```csharp
private async Task CallService()
{
   using var scope = Baggage.Attach(Baggage.Create().SetBaggage("MyKey", "MyValue"));

   await client.SayHelloAsync(
       new HelloRequest { Name = "World" });
}
```

**Incoming instrumentation** is more interesting (probably what you meant to link to :smile:).

If I'm catching your drift, you are looking for a way to do this that doesn't involve holding onto something which must be disposed.

I just updated the AspNetCore instrumentation on this PR. What I did there is if we detect `AsyncLocal` in play, we don't dispose anything. We know AspNetCore does the right thing with `ExecutionContext`. But if we're not doing `AsyncLocal`, we will manage the lifetime of the scope.

We could possibly make a different API but I'm a bit hesistant to do that because the spec has a **MUST** for the [Detach](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/context#detach-context):

> The API MUST accept the following parameters:
>
> A Token that was returned by a previous call to attach a Context.

I took a look at some of the other instrumentation in contrib (Owin, AspNet, WCF, etc.) and it won't take much effort to fix them up becuase they already have container things to track the `Activity` to clean up when finished.

If you have any ideas though I'm happy to explore them.

**Comment by czadokonradnetigate** [comment]
Any updates on that one?

**Pull request closed without merging**
