### PR TITLE
Get rid of OpenTelemetry.Exporter.Console namespace

### PR DESCRIPTION
**Pull request by reyang**
I guess it might be better to have `OpenTelemetry.Exporter.ConsoleExporter` instead of `OpenTelemetry.Exporter.Console.ConsoleExporter`?
* Removing the extra `Console` namespace doesn't seem to introduce a big naming pollution/confusion.
* We don't have to struggle with the conflict with `System.Console` anymore.

Trying to see if folks like this idea and should we do the same thing for all other exporters.

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by eddynaka — COMMENTED** [review]
Based on the description of the issue, I was expecting to see a change from . console to .consoleexporter.

Should we add a change in changeling, since it's affecting public classes?

**Comment by reyang** [comment]
> Should we add a change in changelog, since it's affecting public classes?

I don't have a strong opinion on this. Looks like most of the cases folks will use `AddConsoleExporter` which is not affected by the namespace change.

**Comment by eddynaka** [comment]
> > Should we add a change in changelog, since it's affecting public classes?
> 
> I don't have a strong opinion on this. Looks like most of the cases folks will use `AddConsoleExporter` which is not affected by the namespace change.

If that's the case, should we change to private? less public methods. What do you think?

**Comment by CodeBlanch** [comment]
New namespace works for me. If we do that for all exporters we just need to make sure anything public has a good name `ConsoleWhatnot` in case people happen to use multiple exporters. For example, let's say Jaeger had public class OpenTelemetry.Exporter.ExporterOptions & Zipkin had public class OpenTelemetry.Exporter.ExporterOptions that could cause headaches for anyone using both. Names like JaegerExporterOptions & ZipkinExporterOptions would be fine.

**Pull request merged**
