### PR TITLE
Add more StackDriver labels

### LINKED ISSUE #470: Stackdriver Trace - wrong label used for http user_agent
Following this reference here: https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#TraceSpan

the `/http/user_agent` should be used - the `/agent` is reserved for the name of the tracing agent.

#453 did introduce replacing of some of the labels - but might have replace http user agent with the wrong label

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Fixes  #470.

Updates SD label from `/agent` to `/http/user_agent`.

@nmbro

### CODE REVIEW

**Comment by nmbro** [comment]
Also where we are here - there's actually a `/http/path` and `/http/url` might fit the `http.rawurl` better?

**Comment by nmbro** [comment]
@MikeGoldsmith I added the changes here: https://github.com/MikeGoldsmith/opentelemetry-dotnet/pull/1

**Comment by MikeGoldsmith** [comment]
Looks great, thanks for the extra properties @mbro.

**Comment by MikeGoldsmith** [comment]
@nmbro please can you sign the [CNCF CLA](https://identity.linuxfoundation.org/projects/cncf)? We won't be able to merge until then you've contributed a commit and all commitors need to have signed.

**Comment by nmbro** [comment]
@MikeGoldsmith I started the process

**Comment by nmbro** [comment]
I signed it

**Comment by SergeyKanzhelev** [comment]
@nmbro sometimes the problem is that commits include some merge commit with many names associated with it. Or your GitHub is configured for the different e-mail address. I'd suggest to squash your commits and check the commit e-mail

**Comment by nmbro** [comment]
```
Neither the email on the ICLA (captured from you Linux Foundation ID profile when you signed) nor the current email on the profile matters for passing the GitHub check.

For a PR to pass, each commit must pass this check: the Github user that the commit is attributed to (based on a match between the commit authorship and Github profile) must be linked to a Linux Foundation ID user (on the "social network logins" tab), who is authorized by a signed ICLA and/or a CCLA.
```
My github user is already on the social network logins tab of my cncf account.

**Comment by nmbro** [comment]
My commit is even gpg signed with my corporate email and verified by github - surely there's something goofy going on, on the cncf checker if it's not passing.

**Comment by nmbro** [comment]
I added myself to the "Contributing employee" group - lets see if that made a difference, before I was only an "Organization manager"

**Comment by nmbro** [comment]
GREEN BABY! 💯

**Comment by MikeGoldsmith** [comment]
@open-telemetry/dotnet-approvers ping - this is a simple change, just adding more labels to swap out for StackDriver versions.

**Pull request merged**
