### PR TITLE
Build OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj based on latest .proto files

### PR DESCRIPTION
**Pull request by pcwiese**
.proto files forked from https://github.com/open-telemetry/opentelemetry-proto
@4b6ff88e525739a2b1d2cbed619301076c6687e7

Generate the .cs files from the .proto files using Grpc.Tools.

Related:
https://github.com/open-telemetry/opentelemetry-dotnet/issues/19

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
perhaps add a file with the SHA of a copy in the repository

**Comment by pcwiese** [comment]
> I didn't review much, but looks good after the first glance. Do you want it merged right away?

Certainly not urgent. Just trying to get something flowing from C# to the otelcol container for testing.

**Comment by SergeyKanzhelev** [comment]
@pcwiese no, you are correct. I believe the work is planned though. I saw you following up on gitter on this.

Let's keep it in PR for a bit and once there is a timeline we can move it forward

**Comment by SergeyKanzhelev** [comment]
Actually, let's merge this in as we already have project merged. Do you mind renaming the project to `OTCollector`?

**Comment by pcwiese** [comment]
Sure I can rename it

**Comment by pcwiese** [comment]
I 100% agree with all of your comments here.

I'm aware the current .protos aren't spec approved compliant and I had no plans to update this until the actual collector receiver was in place anyway. So it might be too early. I added it back because I inadvertently thought the collector had some otel protocol receiver available; but this is none at all right now.

The exporter itself needs a bunch of work, agreed.
I intentionally did not update the README because people shouldn't be using yet.

I do think there is value in getting this in though. There are plenty of tasks for someone to do apart from the transformation from OpenTelemetry SDK constructs to wire protocol constructs.

Happy to shelve this for now, or just get it in and keep it in sync when the .protos change.

**Comment by lmolkova** [comment]
@pcwiese I'm fine with merging it as long as we figure out naming.

 @SergeyKanzhelev what is the motivation for `OTCollector` and can we name it differently?
According to the spec, [collector](https://github.com/open-telemetry/opentelemetry-specification/blob/1342b5d964af5112072ae75a812729914f882168/specification/overview.md#collector) is rather daemon or service. 

Can we call it  
- Otprocotol (like java)   - I'm not fun, but its better than collector
- Otlp (this is spec abbreviation for the protocol)
- OtCollector or Otcollector if it has to be called collector?

**Comment by pcwiese** [comment]
I vote for either Otlp or just OpenTelemetryProtocol (despite being a bit redundant). Usually I am favor of spelling things out to reduce confusion.

**Comment by SergeyKanzhelev** [comment]
Full name of the package is `OpenTelemtery.Exporter.OTCollector` similar to `OpenTelemtery.Exporter.Jaeger`. So it is hard to confuse with the daemon. But I'm fine with `OpenTelemetryProtocol`.

**Comment by pcwiese** [comment]
I'll go with OpenTelemetryProtocol then.

**Comment by SergeyKanzhelev** [comment]
let's handle adding extension method in separate PR. Merging this one

**Pull request merged**
