### PR TITLE
[sdk-logs] Support enrichment of LogRecords

### PR DESCRIPTION
**Pull request by CodeBlanch**
[Opening as a draft to discuss if this is something we want to do.]

## Changes

* Adds `AddAtribute` API on `LogRecord` to give users wanting to do enrichment a very efficient way to do it

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by cijothomas** [comment]
Haven't checked the actual code, but a quick thought.
Should we explore and confirm the ILogger's native support for this? ILogger is introducing dynamic filtering, so it makes sense if enrichment of Logs are also handled in ILogger itself.

https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions#log-enrichment this looks ready, but haven't tested myself.

**Comment by cijothomas** [comment]
@dariusclay to comment on plans for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.Enrichment as well. We should try and keep a single solution, unless there is a strong reason to have multiple...

**Comment by CodeBlanch** [comment]
@cijothomas 

To add some context here...

The use case I got from @vishweshbankwar is for AzureMonitor which wants to modify [this processor](https://github.com/Azure/azure-sdk-for-net/blob/edd4ad4ff6593f418ad567be6ccc2aad0088fa6e/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/LogFilteringProcessor.cs#L20) to be something like...

```csharp
        public override void OnEnd(LogRecord logRecord)
        {
            if (logRecord.SpanId == default || logRecord.TraceFlags == ActivityTraceFlags.Recorded)
            {
                logRecord.AddAttribute(new KeyValuePair<string, object?>("azureMonitor.samplingRate", value));

                base.OnEnd(logRecord);
            }
        }
```

Some thoughts...

SDK supports enrichment today because `LogRecord.Attributes` has `public` get/set (as does most everything on `LogRecord`) but the contract is `IReadOnlyList` which makes it tricky. Worse case users will make a complete copy of the list and replace it (allocation + cpu cost). Best case they will do what this PR does and wrap the list but they will still need to pay for an allocation. What this PR does is give a nice cheap (no allocation after pool warms up, very minor CPU hit) way to do it efficiently. Also a potential mechanism the SDK itself could utilize in the future to add its own attributes instead of adding properties to `LogRecord` and asking exporters to work with them.

* Could AzureMonitor use `Microsoft.Extensions.Telemetry.Abstractions` or `OpenTelemetry.Extensions.Enrichment`? Perhaps, but I doubt the distro wants to be that opinionated.
  * `OpenTelemetry.Extensions.Enrichment` doesn't support logging at the moment. When it does, it will face the same performance issues as above. It could use this proposed API though to accomplish its goal. 
  * `Microsoft.Extensions.Telemetry.Abstractions` does support enrichment, but it also completely replaces the `ILoggerFactory` with its own implementation. Not sure if AzureMonitor could/would want to do that.

* Should we look at `ILogger` doing enrichment? Yes! I did a prototype myself a while back 🤣 Most logging frameworks (serilog, nlog, log4net, etc.) have their own enrichment APIs. IMO these are user-facing APIs for the devs setting up their logging pipelines. That is kind of a different thing though. This PR is more of a low-level thing for SDK components (really processors). But aspiring devs can build rich, fully-featured, user-facing frameworks on top of it for fun and profit 💸

**Review by reyang — CHANGES_REQUESTED** [review]
I suggest that we should first align on where enrichment should happen, and discuss this with the owners of ILogger and Microsoft.Extensions.Telemetry.Abstractions, so we don't end up with 3 confusing mechanisms while each solving 80% of the problems.

One approach would be documenting the end goal / experience before the actual implementation https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs#log-enrichment

**Comment by CodeBlanch** [comment]
Alignment? 🤔

> ## LogRecordProcessor
>
> ...
>
> The SDK MUST allow users to implement and configure custom processors and decorate built-in processors for advanced scenarios such as enriching with attributes.

We MUST support specifically enrichment via processors. Which we already do. The question is: Do we want to make it efficient and easy to do or no?

**Comment by dariusclay** [comment]
> @dariusclay to comment on plans for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.Enrichment as well. We should try and keep a single solution, unless there is a strong reason to have multiple...

The extensions mentioned here were to bridge the gap in current .NET 8 support for trace enrichment. I will try to get an update but from last time this was spoken about internally the goal was to have proper trace enrichment natively inside .NET 9.

**Comment by dariusclay** [comment]
>   * `Microsoft.Extensions.Telemetry.Abstractions` does support enrichment, but it also completely replaces the `ILoggerFactory` with its own implementation. Not sure if AzureMonitor could/would want to do that.
> * Should we look at `ILogger` doing enrichment? Yes! I did a prototype myself a while back 🤣 Most logging frameworks (serilog, nlog, log4net, etc.) have their own enrichment APIs. IMO these are user-facing APIs for the devs setting up their logging pipelines. That is kind of a different thing though. This PR is more of a low-level thing for SDK components (really processors). But aspiring devs can build rich, fully-featured, user-facing frameworks on top of it for fun and profit 💸

The "extended" logger is what enables redaction and enrichment. 
https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLoggerFactory.cs

**Pull request closed without merging**
