### PR TITLE
Mark DiagnosticSource subscription helpers as internal

### PR DESCRIPTION
**Pull request by cijothomas**
Step 4 from https://github.com/open-telemetry/opentelemetry-dotnet/issues/1437#issuecomment-721600383

### CODE REVIEW

**Review by reyang — APPROVED** [review]
LGTM.

**Comment by ejsmith** [comment]
I really don't like this set of changes. When did you decide to make PropertyFetcher internal? Didn't you guys just decide to make it public not that long ago? What I REALLY hate is that you are cheating in your instrumentation libraries by using `InternalsVisibleTo`. IMO, that is hostile to the community of people trying to build non-official instrumentations around your library and you guys won't feel the pain you are causing because you are cheating in your own instrumentations.

**Comment by ejsmith** [comment]
And I'm not just talking about `PropertyFetcher`. Making `DiagnosticSourceSubscriber` and other classes internal sucks. If you are going to make these changes then I think you should get rid of the `InternalsVisibleTo` and build your instrumentations using the same set of APIs that 3rd party instrumentations have access to.

**Comment by reyang** [comment]
> And I'm not just talking about `PropertyFetcher`. Making `DiagnosticSourceSubscriber` and other classes internal sucks. If you are going to make these changes then I think you should get rid of the `InternalsVisibleTo` and build your instrumentations using the same set of APIs that 3rd party instrumentations have access to.

@ejsmith that is the goal. It comes with 3 steps:
1. review all the APIs and remove the ones that are not supposed to be public.
2. workaround the dependencies to unblock the GA release.
3. clean up the dependency (e.g. OpenTelemetry package should have no knowledge about upper level packages such like exporter and instrumentation library).

What you've seen is part of the step 2 effort. It seems your concerns were caused by the lack of context - please refer to the PR description to get a better understanding (which points to #1437).

**Comment by ejsmith** [comment]
@reyang @CodeBlanch @cijothomas so what exactly is the plan? I am looking at the contrib project and everything is broken now. Am I supposed to source copy the things that were being used down to these projects?

**Comment by cijothomas** [comment]
> @reyang @CodeBlanch @cijothomas so what exactly is the plan? I am looking at the contrib project and everything is broken now. Am I supposed to source copy the things that were being used down to these projects?

https://github.com/open-telemetry/opentelemetry-dotnet/issues/1437 Please look at this issue and share comments/concerns/questions there. It's easy to track conversation that way.

**Pull request merged**
